<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PublishAot Condition="'$(PublishAot)' == ''">true</PublishAot>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Doroti.Framework.Painting/Doroti.Framework.Painting.csproj" />
  </ItemGroup>
</Project>
