using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using Doroti.Tooling;

namespace Doroti.DartToCSharp;

internal sealed partial class FrameworkCSharpLowerer
{
    private readonly FrameworkSemanticIndex _semanticIndex;
    private readonly FrameworkAstIndex _astIndex;
    private readonly IReadOnlySet<string> _generatedDeclarationIds;
    private readonly FrameworkLoweringSession _session = new();
    private readonly CoreResolvedDeclaration[] _currentDeclarations;
    private readonly string _currentLibrary;
    private readonly HashSet<string> _activeTypeMappings = new(StringComparer.Ordinal);

    public FrameworkCSharpLowerer(LibraryCompilationContext context)
    {
        _semanticIndex = context.Compilation.SemanticIndex;
        _astIndex = context.Compilation.AstIndex;
        _generatedDeclarationIds = context.Compilation.GeneratedDeclarationIds;
        _currentDeclarations = context.Declarations;
        _currentLibrary = context.Library;
    }

    public GeneratedFile Generate(
        string outputNamespace,
        string package,
        string library,
        string inputPath,
        List<ConverterDiagnostic> diagnostics)
    {
        var builder = new CsSyntaxBuilder();
        var declarationOrigins = new List<(CoreResolvedDeclaration Declaration, CsOrigin Origin)>();
        var preservesG31Artifact = IsPinnedG31CompatibilityLibrary(library);
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        if (!preservesG31Artifact)
        {
            builder.AppendLine("#pragma warning disable CS0108, CS0114, CS0162, CS0168, CS0659, CS0675, CS0693, CS4014, CS8321, CS8600, CS8601, CS8602, CS8603, CS8604, CS8605, CS8609, CS8613, CS8619, CS8620, CS8622, CS8625, CS8629, CS8714, CS8765, CS8767, CS8981");
        }
        builder.AppendLine($"// Doroti typed semantic compiler {CompilerVersions.Converter}; source: {ArtifactFiles.NormalizePath(inputPath)}");
        builder.AppendLine("using System;");
        if (!preservesG31Artifact)
        {
            builder.AppendLine("using System.Collections.Generic;");
            // Import only the runtime type emitted by the lowerer. Importing
            // the namespace makes Flutter's Material Switch ambiguous with
            // System.Diagnostics.Switch in generated application sources.
            builder.AppendLine("using Stopwatch = System.Diagnostics.Stopwatch;");
            builder.AppendLine("using System.Linq;");
            builder.AppendLine("using System.Threading.Tasks;");
        }
        builder.AppendLine("using Doroti.Runtime;");
        if (!preservesG31Artifact)
        {
            builder.AppendLine("using Doroti.Ui;");
            builder.AppendLine("using static Doroti.Runtime.FoundationRuntimePorts;");
            builder.AppendLine("using Match = Doroti.Runtime.DartMatch;");
            if (library.EndsWith("/rendering/binding.dart", StringComparison.Ordinal))
            {
                builder.AppendLine("using SemanticsBinding = global::Doroti.Framework.Semantics.SemanticsBinding;");
            }
        }
        builder.AppendLine();
        builder.AppendLine($"namespace {outputNamespace};");
        builder.AppendLine();
        if (library.EndsWith("/widgets/framework.dart", StringComparison.Ordinal))
        {
            EmitStateRuntimeContract(builder);
        }

        _session.EmittingAssignmentLeft = false;
        foreach (var declaration in _currentDeclarations.OrderBy(item => item.Offset))
        {
            if (declaration.Ast.Kind == CoreNodeKind.FunctionDeclaration &&
                declaration.Ast.Text(CoreProperty.isSetter) == "true" &&
                _currentDeclarations.Any(item => item.Name == declaration.Name && item.Ast.Text(CoreProperty.isGetter) == "true"))
            {
                continue;
            }
            var origin = new CsOrigin(
                ArtifactFiles.NormalizePath(inputPath),
                declaration.Offset,
                declaration.Length,
                declaration.Element.Symbol.Value);
            declarationOrigins.Add((declaration, origin));
            using (builder.BeginRegion(CsSyntaxRegionKind.Declaration, origin))
            {
                var previousSubstitutions = _session.TypeParameterSubstitutions;
                var previousDeclaration = _session.ActiveDeclaration;
                _session.ActiveDeclaration = declaration;
                _session.TypeParameterSubstitutions = DeclarationTypeParameterSubstitutions(declaration);
                try
                {
                    if (TryEmitPinnedG31Declaration(builder, declaration, library))
                    {
                        continue;
                    }
                    switch (declaration.Ast.Kind)
                    {
                        case CoreNodeKind.FunctionDeclaration:
                            EmitTopLevelFunction(builder, declaration, package, library, inputPath, diagnostics);
                            break;
                        case CoreNodeKind.ClassDeclaration:
                        case CoreNodeKind.ExtensionTypeDeclaration:
                        case CoreNodeKind.MixinDeclaration:
                            EmitClass(builder, declaration, package, library, inputPath, diagnostics);
                            break;
                        case CoreNodeKind.ExtensionDeclaration:
                            EmitExtension(builder, declaration, package, library, inputPath, diagnostics);
                            break;
                        case CoreNodeKind.TopLevelVariableDeclaration:
                            EmitTopLevelVariable(builder, declaration, package, library, inputPath, diagnostics);
                            break;
                        case CoreNodeKind.EnumDeclaration:
                            EmitEnum(builder, declaration, package, library, inputPath, diagnostics);
                            break;
                        case CoreNodeKind.GenericTypeAlias:
                            EmitTypeAlias(builder, declaration);
                            break;
                        default:
                            AddUnsupportedDiagnostic(diagnostics, package, library, inputPath, declaration, declaration.Ast,
                                "declaration", "Add a typed declaration visitor before expanding the selected framework closure.");
                            break;
                    }
                }
                finally
                {
                    _session.TypeParameterSubstitutions = previousSubstitutions;
                    _session.ActiveDeclaration = previousDeclaration;
                }
            }
        }
        if (library.EndsWith("/widgets/widget_inspector.dart", StringComparison.Ordinal))
        {
            builder.AppendLine($"public static partial class {LibraryStaticClassName(library)}");
            builder.AppendLine("{");
            builder.AppendLine("    public static class developer");
            builder.AppendLine("    {");
            builder.AppendLine("        public static class CreationLocation");
            builder.AppendLine("        {");
            builder.AppendLine("            public static global::Doroti.Runtime.CreationLocation? of(object? value) => global::Doroti.Runtime.CreationLocation.of(value);");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            builder.AppendLine();
        }

        var printed = new CSharpPrinter().Print(builder.Build());
        var printedByOrigin = printed.Origins.ToDictionary(item => item.Origin);
        var mappings = declarationOrigins.Select(item =>
        {
            var printedOrigin = printedByOrigin[item.Origin];
            return new SourceMapEntry(
                inputPath,
                item.Declaration.Offset,
                item.Declaration.Length,
                item.Declaration.Name,
                string.Empty,
                printedOrigin.StartLine,
                printedOrigin.EndLine,
                "typed-semantic");
        }).ToArray();
        return new(ApplyG53FrameworkCompatibility(library, printed.Text), mappings);
    }

    private static void EmitStateRuntimeContract(CsSyntaxBuilder builder)
    {
        builder.AppendLine("/// <summary>Non-generic CLR contract for Dart's raw State type.</summary>");
        builder.AppendLine("public interface IState");
        builder.AppendLine("{");
        builder.AppendLine("    StatefulWidget? _widget { get; set; }");
        builder.AppendLine("    _StateLifecycle__framework _debugLifecycleState { get; set; }");
        builder.AppendLine("    StatefulElement? _element { get; set; }");
        builder.AppendLine("    StatefulWidget widget { get; }");
        builder.AppendLine("    BuildContext context { get; }");
        builder.AppendLine("    bool mounted { get; }");
        builder.AppendLine("    void initState();");
        builder.AppendLine("    void didUpdateWidget(StatefulWidget oldWidget);");
        builder.AppendLine("    void reassemble();");
        builder.AppendLine("    void setState(global::System.Action fn);");
        builder.AppendLine("    void deactivate();");
        builder.AppendLine("    void activate();");
        builder.AppendLine("    void dispose();");
        builder.AppendLine("    Widget build(BuildContext context);");
        builder.AppendLine("    void didChangeDependencies();");
        builder.AppendLine("}");
        builder.AppendLine();
    }

}
