<Project>
  <ItemGroup Condition="'$(DorotiTarget)' == 'Android' and '@(DorotiTargetDescriptor)' == ''">
    <DorotiTargetDescriptor Include="Android" HostKind="Maui" NativeEntryKind="Android-Application" RuntimeIdentifier="android-arm64" TargetFramework="net10.0-android" TargetPackage="Doroti.Target.Android.Maui.android-arm64" />
  </ItemGroup>
</Project>
