<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Doroti.Flutter.Framework.Rendering</AssemblyName>
    <PackageId>Doroti.Flutter.Framework.Rendering</PackageId>
    <IsDorotiProduct>true</IsDorotiProduct>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Doroti.Generated.Framework.Widgets.Widgets" />
    <InternalsVisibleTo Include="Doroti.Flutter.Framework.Widgets" />
    <ProjectReference Include="..\Doroti.Flutter.Runtime\Doroti.Flutter.Runtime.csproj" />
    <ProjectReference Include="..\Doroti.Flutter.Ui\Doroti.Flutter.Ui.csproj" />
    <ProjectReference Include="..\Doroti.Flutter.Framework.Foundation\Doroti.Flutter.Framework.Foundation.csproj" />
    <ProjectReference Include="..\Doroti.Flutter.Framework.Scheduler\Doroti.Flutter.Framework.Scheduler.csproj" />
    <ProjectReference Include="..\Doroti.Flutter.Framework.Services\Doroti.Flutter.Framework.Services.csproj" />
    <ProjectReference Include="..\Doroti.Flutter.Framework.Physics\Doroti.Flutter.Framework.Physics.csproj" />
    <ProjectReference Include="..\Doroti.Flutter.Framework.Animation\Doroti.Flutter.Framework.Animation.csproj" />
    <ProjectReference Include="..\Doroti.Flutter.Framework.Gestures\Doroti.Flutter.Framework.Gestures.csproj" />
    <ProjectReference Include="..\Doroti.Flutter.Framework.Painting\Doroti.Flutter.Framework.Painting.csproj" />
    <ProjectReference Include="..\Doroti.Flutter.Framework.Semantics\Doroti.Flutter.Framework.Semantics.csproj" />
  </ItemGroup>
</Project>
