<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Doroti.Flutter.Ui</AssemblyName>
    <PackageId>Doroti.Flutter.Ui</PackageId>
    <IsDorotiProduct>true</IsDorotiProduct>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Doroti.Host.Desktop.Flutter" />
    <ProjectReference Include="..\Doroti.Flutter.Runtime\Doroti.Flutter.Runtime.csproj" />
  </ItemGroup>
</Project>
