<Project>
  <ItemGroup Condition="'$(DorotiTarget)' == 'iOS' and '@(DorotiTargetDescriptor)' == ''">
    <DorotiTargetDescriptor Include="iOS" HostKind="Maui" NativeEntryKind="UIKit-Main" RuntimeIdentifier="ios-arm64" TargetFramework="$(TargetFramework)" TargetPackage="Doroti.Target.iOS.Maui.ios-arm64" />
  </ItemGroup>
</Project>
