// Generated by generate-dispatch.py; edit the generator and regenerate.
using System.Runtime.InteropServices;
using Silk.NET.Vulkan;
using VkDevice = Silk.NET.Vulkan.Device;
using VkImage = Silk.NET.Vulkan.Image;
using VkFramebuffer = Silk.NET.Vulkan.Framebuffer;
namespace Doroti.Skia.Vulkan;
internal sealed unsafe partial class VulkanObserver
{
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate Result CreateImageDelegate(VkDevice d, ImageCreateInfo* p, AllocationCallbacks* a, VkImage* output);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void DestroyImageDelegate(VkDevice d, VkImage image, AllocationCallbacks* a);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate Result CreateImageViewDelegate(VkDevice d, ImageViewCreateInfo* p, AllocationCallbacks* a, ImageView* output);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void DestroyImageViewDelegate(VkDevice d, ImageView view, AllocationCallbacks* a);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate Result CreateRenderPassDelegate(VkDevice d, RenderPassCreateInfo* p, AllocationCallbacks* a, RenderPass* output);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate Result CreateRenderPass2Delegate(VkDevice d, RenderPassCreateInfo2* p, AllocationCallbacks* a, RenderPass* output);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void DestroyRenderPassDelegate(VkDevice d, RenderPass pass, AllocationCallbacks* a);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate Result CreateFramebufferDelegate(VkDevice d, FramebufferCreateInfo* p, AllocationCallbacks* a, VkFramebuffer* output);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void DestroyFramebufferDelegate(VkDevice d, VkFramebuffer frame, AllocationCallbacks* a);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate Result AllocateCommandBuffersDelegate(VkDevice d, CommandBufferAllocateInfo* p, CommandBuffer* output);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void FreeCommandBuffersDelegate(VkDevice d, CommandPool pool, uint count, CommandBuffer* buffers);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate Result BeginCommandBufferDelegate(CommandBuffer cb, CommandBufferBeginInfo* p);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate Result EndCommandBufferDelegate(CommandBuffer cb);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate Result ResetCommandBufferDelegate(CommandBuffer cb, CommandBufferResetFlags flags);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate Result ResetCommandPoolDelegate(VkDevice d, CommandPool pool, CommandPoolResetFlags flags);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void DestroyCommandPoolDelegate(VkDevice d, CommandPool pool, AllocationCallbacks* a);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void CmdPipelineBarrierDelegate(CommandBuffer cb, PipelineStageFlags src, PipelineStageFlags dst, DependencyFlags flags, uint memoryCount, MemoryBarrier* memory, uint bufferCount, BufferMemoryBarrier* buffers, uint imageCount, ImageMemoryBarrier* images);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void CmdWaitEventsDelegate(CommandBuffer cb, uint count, Silk.NET.Vulkan.Event* events, PipelineStageFlags src, PipelineStageFlags dst, uint memoryCount, MemoryBarrier* memory, uint bufferCount, BufferMemoryBarrier* buffers, uint imageCount, ImageMemoryBarrier* images);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void CmdPipelineBarrier2Delegate(CommandBuffer cb, DependencyInfo* dependency);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void CmdWaitEvents2Delegate(CommandBuffer cb, uint count, Silk.NET.Vulkan.Event* events, DependencyInfo* dependencies);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void CmdSetEvent2Delegate(CommandBuffer cb, Silk.NET.Vulkan.Event e, DependencyInfo* dependency);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void CmdBeginRenderPassDelegate(CommandBuffer cb, RenderPassBeginInfo* p, SubpassContents contents);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void CmdNextSubpassDelegate(CommandBuffer cb, SubpassContents contents);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void CmdEndRenderPassDelegate(CommandBuffer cb);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void CmdBeginRenderPass2Delegate(CommandBuffer cb, RenderPassBeginInfo* p, SubpassBeginInfo* begin);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void CmdNextSubpass2Delegate(CommandBuffer cb, SubpassBeginInfo* begin, SubpassEndInfo* end);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void CmdEndRenderPass2Delegate(CommandBuffer cb, SubpassEndInfo* end);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void CmdBeginRenderingDelegate(CommandBuffer cb, RenderingInfo* p);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void CmdEndRenderingDelegate(CommandBuffer cb);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate void CmdExecuteCommandsDelegate(CommandBuffer cb, uint count, CommandBuffer* children);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate Result QueueSubmitDelegate(Queue q, uint count, SubmitInfo* submits, Fence fence);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate Result QueueSubmit2Delegate(Queue q, uint count, SubmitInfo2* submits, Fence fence);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate Result QueueBindSparseDelegate(Queue q, uint count, BindSparseInfo* binds, Fence fence);
    private Delegate? Wrap(string name, nint address)
    {
        switch (name)
        {
            case "vkCreateImage":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<CreateImageDelegate>(address);
                return new CreateImageDelegate((d, p, a, output) =>
                {
                    var result = forward(d, p, a, output);
                    Observe(() => { if (result == Result.Success) CreatedImage(d, p, output); });
                    return result;
                });
            }
            case "vkDestroyImage":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<DestroyImageDelegate>(address);
                return new DestroyImageDelegate((d, image, a) =>
                {
                    forward(d, image, a);
                    Observe(() => { Device(d); Images.Remove(image.Handle); Journal.RemoveImage(image.Handle); });
                });
            }
            case "vkCreateImageView":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<CreateImageViewDelegate>(address);
                return new CreateImageViewDelegate((d, p, a, output) =>
                {
                    var result = forward(d, p, a, output);
                    Observe(() => { if (result == Result.Success) CreatedView(d, p, output); });
                    return result;
                });
            }
            case "vkDestroyImageView":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<DestroyImageViewDelegate>(address);
                return new DestroyImageViewDelegate((d, view, a) =>
                {
                    forward(d, view, a);
                    Observe(() => { Device(d); Views.Remove(view.Handle); });
                });
            }
            case "vkCreateRenderPass":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<CreateRenderPassDelegate>(address);
                return new CreateRenderPassDelegate((d, p, a, output) =>
                {
                    var result = forward(d, p, a, output);
                    Observe(() => { if (result == Result.Success) CreatedPass(d, p, output); });
                    return result;
                });
            }
            case "vkCreateRenderPass2":
            case "vkCreateRenderPass2KHR":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<CreateRenderPass2Delegate>(address);
                return new CreateRenderPass2Delegate((d, p, a, output) =>
                {
                    var result = forward(d, p, a, output);
                    Observe(() => { if (result == Result.Success) CreatedPass2(d, p, output); });
                    return result;
                });
            }
            case "vkDestroyRenderPass":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<DestroyRenderPassDelegate>(address);
                return new DestroyRenderPassDelegate((d, pass, a) =>
                {
                    forward(d, pass, a);
                    Observe(() => { Device(d); Passes.Remove(pass.Handle); });
                });
            }
            case "vkCreateFramebuffer":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<CreateFramebufferDelegate>(address);
                return new CreateFramebufferDelegate((d, p, a, output) =>
                {
                    var result = forward(d, p, a, output);
                    Observe(() => { if (result == Result.Success) CreatedFramebuffer(d, p, output); });
                    return result;
                });
            }
            case "vkDestroyFramebuffer":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<DestroyFramebufferDelegate>(address);
                return new DestroyFramebufferDelegate((d, frame, a) =>
                {
                    forward(d, frame, a);
                    Observe(() => { Device(d); Framebuffers.Remove(frame.Handle); });
                });
            }
            case "vkAllocateCommandBuffers":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<AllocateCommandBuffersDelegate>(address);
                return new AllocateCommandBuffersDelegate((d, p, output) =>
                {
                    var result = forward(d, p, output);
                    Observe(() => { if (result == Result.Success) Allocated(d, p, output); });
                    return result;
                });
            }
            case "vkFreeCommandBuffers":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<FreeCommandBuffersDelegate>(address);
                return new FreeCommandBuffersDelegate((d, pool, count, buffers) =>
                {
                    forward(d, pool, count, buffers);
                    Observe(() => { Freed(d, count, buffers); });
                });
            }
            case "vkBeginCommandBuffer":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<BeginCommandBufferDelegate>(address);
                return new BeginCommandBufferDelegate((cb, p) =>
                {
                    var result = forward(cb, p);
                    Observe(() => { if (result == Result.Success) { Journal.Begin(cb.Handle); ActivePasses.Remove(cb.Handle); if (p->PInheritanceInfo != null && p->PInheritanceInfo->RenderPass.Handle != 0) throw new NotSupportedException("Inherited render-pass secondary unsupported."); } });
                    return result;
                });
            }
            case "vkEndCommandBuffer":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<EndCommandBufferDelegate>(address);
                return new EndCommandBufferDelegate((cb) =>
                {
                    var result = forward(cb);
                    Observe(() => { if (result == Result.Success) { if (ActivePasses.ContainsKey(cb.Handle)) throw new InvalidOperationException("Open pass at EndCommandBuffer."); Journal.End(cb.Handle); } });
                    return result;
                });
            }
            case "vkResetCommandBuffer":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<ResetCommandBufferDelegate>(address);
                return new ResetCommandBufferDelegate((cb, flags) =>
                {
                    var result = forward(cb, flags);
                    Observe(() => { if (result == Result.Success) { Journal.Begin(cb.Handle); ActivePasses.Remove(cb.Handle); } });
                    return result;
                });
            }
            case "vkResetCommandPool":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<ResetCommandPoolDelegate>(address);
                return new ResetCommandPoolDelegate((d, pool, flags) =>
                {
                    var result = forward(d, pool, flags);
                    Observe(() => { if (result == Result.Success) ResetPool(d, pool, false); });
                    return result;
                });
            }
            case "vkDestroyCommandPool":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<DestroyCommandPoolDelegate>(address);
                return new DestroyCommandPoolDelegate((d, pool, a) =>
                {
                    forward(d, pool, a);
                    Observe(() => { ResetPool(d, pool, true); });
                });
            }
            case "vkCmdPipelineBarrier":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<CmdPipelineBarrierDelegate>(address);
                return new CmdPipelineBarrierDelegate((cb, src, dst, flags, memoryCount, memory, bufferCount, buffers, imageCount, images) =>
                {
                    forward(cb, src, dst, flags, memoryCount, memory, bufferCount, buffers, imageCount, images);
                    Observe(() => { Barrier(cb.Handle, imageCount, images); });
                });
            }
            case "vkCmdWaitEvents":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<CmdWaitEventsDelegate>(address);
                return new CmdWaitEventsDelegate((cb, count, events, src, dst, memoryCount, memory, bufferCount, buffers, imageCount, images) =>
                {
                    forward(cb, count, events, src, dst, memoryCount, memory, bufferCount, buffers, imageCount, images);
                    Observe(() => { Barrier(cb.Handle, imageCount, images); });
                });
            }
            case "vkCmdPipelineBarrier2":
            case "vkCmdPipelineBarrier2KHR":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<CmdPipelineBarrier2Delegate>(address);
                return new CmdPipelineBarrier2Delegate((cb, dependency) =>
                {
                    forward(cb, dependency);
                    Observe(() => { Barrier2(cb.Handle, dependency); });
                });
            }
            case "vkCmdWaitEvents2":
            case "vkCmdWaitEvents2KHR":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<CmdWaitEvents2Delegate>(address);
                return new CmdWaitEvents2Delegate((cb, count, events, dependencies) =>
                {
                    forward(cb, count, events, dependencies);
                    Observe(() => { throw new NotSupportedException("Split synchronization2 events unsupported."); });
                });
            }
            case "vkCmdSetEvent2":
            case "vkCmdSetEvent2KHR":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<CmdSetEvent2Delegate>(address);
                return new CmdSetEvent2Delegate((cb, e, dependency) =>
                {
                    forward(cb, e, dependency);
                    Observe(() => { throw new NotSupportedException("Split synchronization2 events unsupported."); });
                });
            }
            case "vkCmdBeginRenderPass":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<CmdBeginRenderPassDelegate>(address);
                return new CmdBeginRenderPassDelegate((cb, p, contents) =>
                {
                    forward(cb, p, contents);
                    Observe(() => { BeginPass(cb.Handle, p); });
                });
            }
            case "vkCmdNextSubpass":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<CmdNextSubpassDelegate>(address);
                return new CmdNextSubpassDelegate((cb, contents) =>
                {
                    forward(cb, contents);
                    Observe(() => { NextPass(cb.Handle); });
                });
            }
            case "vkCmdEndRenderPass":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<CmdEndRenderPassDelegate>(address);
                return new CmdEndRenderPassDelegate((cb) =>
                {
                    forward(cb);
                    Observe(() => { EndPass(cb.Handle); });
                });
            }
            case "vkCmdBeginRenderPass2":
            case "vkCmdBeginRenderPass2KHR":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<CmdBeginRenderPass2Delegate>(address);
                return new CmdBeginRenderPass2Delegate((cb, p, begin) =>
                {
                    forward(cb, p, begin);
                    Observe(() => { BeginPass(cb.Handle, p); });
                });
            }
            case "vkCmdNextSubpass2":
            case "vkCmdNextSubpass2KHR":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<CmdNextSubpass2Delegate>(address);
                return new CmdNextSubpass2Delegate((cb, begin, end) =>
                {
                    forward(cb, begin, end);
                    Observe(() => { NextPass(cb.Handle); });
                });
            }
            case "vkCmdEndRenderPass2":
            case "vkCmdEndRenderPass2KHR":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<CmdEndRenderPass2Delegate>(address);
                return new CmdEndRenderPass2Delegate((cb, end) =>
                {
                    forward(cb, end);
                    Observe(() => { EndPass(cb.Handle); });
                });
            }
            case "vkCmdBeginRendering":
            case "vkCmdBeginRenderingKHR":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<CmdBeginRenderingDelegate>(address);
                return new CmdBeginRenderingDelegate((cb, p) =>
                {
                    forward(cb, p);
                    Observe(() => { throw new NotSupportedException("Dynamic rendering unsupported in this observer."); });
                });
            }
            case "vkCmdEndRendering":
            case "vkCmdEndRenderingKHR":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<CmdEndRenderingDelegate>(address);
                return new CmdEndRenderingDelegate((cb) =>
                {
                    forward(cb);
                    Observe(() => { throw new NotSupportedException("Dynamic rendering unsupported in this observer."); });
                });
            }
            case "vkCmdExecuteCommands":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<CmdExecuteCommandsDelegate>(address);
                return new CmdExecuteCommandsDelegate((cb, count, children) =>
                {
                    forward(cb, count, children);
                    Observe(() => { for (uint i = 0; i < count; i++) Journal.Secondary(cb.Handle, children[i].Handle); });
                });
            }
            case "vkQueueSubmit":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<QueueSubmitDelegate>(address);
                return new QueueSubmitDelegate((q, count, submits, fence) =>
                {
                    var result = forward(q, count, submits, fence);
                    Observe(() => { Submitted(q, count, submits, result); });
                    return result;
                });
            }
            case "vkQueueSubmit2":
            case "vkQueueSubmit2KHR":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<QueueSubmit2Delegate>(address);
                return new QueueSubmit2Delegate((q, count, submits, fence) =>
                {
                    var result = forward(q, count, submits, fence);
                    Observe(() => { Submitted2(q, count, submits, result); });
                    return result;
                });
            }
            case "vkQueueBindSparse":
            {
                var forward = Marshal.GetDelegateForFunctionPointer<QueueBindSparseDelegate>(address);
                return new QueueBindSparseDelegate((q, count, binds, fence) =>
                {
                    var result = forward(q, count, binds, fence);
                    Observe(() => { throw new NotSupportedException("Sparse binding unsupported."); });
                    return result;
                });
            }
            default:
                if (name.StartsWith("vkCmd", StringComparison.Ordinal) && !PassiveCommands.Contains(name))
                    Observe(() => throw new NotSupportedException("Unknown command entry point: " + name));
                return null;
        }
    }
}
