<Project>
  <PropertyGroup>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' and '$(Configuration)' == 'Release' and '$(DorotiCompilationMode)' != 'Mono' and '$(PublishAot)' != 'false'">ios-arm64</RuntimeIdentifier>
  </PropertyGroup>
  <Import Project="..\Directory.Build.props" />
  <Import Project="../../Doroti/src/Doroti.Runner.Sdk/Sdk/Doroti.IosNativeAot.props" />
  <PropertyGroup>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">iossimulator-arm64</RuntimeIdentifier>
    <BaseIntermediateOutputPath Condition="'$(ArtifactsPath)' == ''">obj\$(RuntimeIdentifier)\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath Condition="'$(ArtifactsPath)' == ''">$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
    <BaseOutputPath Condition="'$(ArtifactsPath)' == ''">bin\$(RuntimeIdentifier)\</BaseOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);obj\**;bin\**</DefaultItemExcludes>
    <NuGetLockFilePath Condition="'$(ArtifactsPath)' == ''">packages.$(RuntimeIdentifier).lock.json</NuGetLockFilePath>
    <NuGetLockFilePath Condition="'$(ArtifactsPath)' != ''">$(ArtifactsPath)/locks/$(MSBuildProjectName)/packages.$(RuntimeIdentifier).lock.json</NuGetLockFilePath>
  </PropertyGroup>
</Project>
