<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><AllowUnsafeBlocks>true</AllowUnsafeBlocks></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Doroti.Skia.Rendering/Doroti.Skia.Rendering.csproj" />
    <PackageReference Include="SkiaSharp.Vulkan.Silk.NET" />
    <PackageReference Include="Silk.NET.Vulkan" />
  </ItemGroup>
</Project>
