<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><AllowUnsafeBlocks>true</AllowUnsafeBlocks></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../samples/DorotiSampleApp2/DorotiSampleApp2.csproj" />
    <ProjectReference Include="../../src/Doroti.Skia.Rendering/Doroti.Skia.Rendering.csproj" />
    <Compile Include="../backdrop-filters/VulkanFixture.cs" Link="VulkanFixture.cs" />
    <PackageReference Include="SkiaSharp.Vulkan.Silk.NET" />
    <PackageReference Include="Silk.NET.Vulkan" />
  </ItemGroup>
</Project>
