global using Doroti.Framework.Animation;
global using Doroti.Cupertino;
global using Doroti.Framework.Foundation;
global using Doroti.Framework.Painting;
global using Doroti.Framework.Rendering;
global using Doroti.Framework.Semantics;
global using Doroti.Framework.Services;
global using Doroti.Framework.Widgets;
global using Path = Doroti.Ui.Path;
global using TextStyle = Doroti.Framework.Painting.TextStyle;
global using Timer = Doroti.Runtime.Timer;

global using Foundation = Doroti.Framework.Foundation;
global using Widgets = Doroti.Framework.Widgets;
global using Rendering = Doroti.Framework.Rendering;
global using Painting = Doroti.Framework.Painting;
global using Services = Doroti.Framework.Services;
global using Animation = Doroti.Framework.Animation;
global using Gestures = Doroti.Framework.Gestures;
global using Physics = Doroti.Framework.Physics;
global using Scheduler = Doroti.Framework.Scheduler;
global using Semantics = Doroti.Framework.Semantics;
