<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="test-data/legacy-manifest.json" LogicalName="Doroti.Application.Manifest" />
    <Compile Remove="windows/**/*.cs" />
    <Compile Remove="macos/**/*.cs" />
    <ProjectReference Include="../../src/Doroti.Hosting/Doroti.Hosting.csproj" />
    <ProjectReference Include="../../src/Doroti.Framework.Services/Doroti.Framework.Services.csproj" />
    <ProjectReference Include="../../src/Doroti.Skia.Rendering/Doroti.Skia.Rendering.csproj" />
  </ItemGroup>
</Project>
