"""Generate the product fallback catalog from the checked-in Flutter reference.

Run from the repository root. No network or build-time reference dependency.
"""
import hashlib
import re
import struct
from pathlib import Path

root = Path(__file__).resolve().parents[2]
source = root / "reference/flutter-master/engine/src/flutter/lib/web_ui/lib/src/engine/font_fallback_data.dart"
target = root / "Doroti/src/Doroti.Host.Web/Fonts"
text = source.read_text(encoding="utf-8")
fonts = re.findall(r"NotoFont\(\s*'([^']+)',\s*'([^']+)',\s*index: (\d+)[,)]", text)
assert fonts and all(int(index) == i for i, (_, _, index) in enumerate(fonts))

def packed(name):
    section = text.split(f"const String {name} =", 1)[1].split(";", 1)[0]
    return "".join(re.findall(r"^\s*'([^']*)'", section, re.M))

components = []
for encoded in packed("encodedFontSets").split(","):
    indices, prefix, previous = [], 0, -1
    for c in encoded:
        if c.isdigit():
            prefix = prefix * 10 + int(c)
        else:
            previous += prefix * 26 + ord(c) - ord('a') + 1
            assert previous < len(fonts)
            indices.append(previous)
            prefix = 0
    components.append(indices)
ranges, end, prefix, size = [], 0, 0, 1
for c in packed("encodedFontSetRanges"):
    if c.isdigit():
        prefix = prefix * 10 + int(c)
    elif 'a' <= c <= 'z':
        size = prefix * 26 + ord(c) - ord('a') + 2
        prefix = 0
    else:
        index = prefix * 26 + ord(c) - ord('A')
        assert index < len(components)
        end += size
        ranges.append((end, index))
        prefix, size = 0, 1
assert end == 0x110000
target.mkdir(parents=True, exist_ok=True)
with (target / "fallbacks.bin").open("wb") as output:
    def integer(value):
        output.write(struct.pack('<I', value))
    def string(value):
        data = value.encode('utf-8')
        integer(len(data))
        output.write(data)
    output.write(b'DFF1')
    integer(len(fonts))
    for name, url, _ in fonts:
        string(name)
        string(url)
    integer(len(components))
    for indices in components:
        integer(len(indices))
        for index in indices:
            integer(index)
    integer(len(ranges))
    for boundary, component in ranges:
        integer(boundary)
        integer(component)
(target / 'LICENSE.flutter.txt').write_bytes((root / 'reference/flutter-master/LICENSE').read_bytes())
(target / 'catalog-source.txt').write_text(
    f'Flutter font_fallback_data.dart SHA256: {hashlib.sha256(source.read_bytes()).hexdigest()}\n'
    f'{len(fonts)} fonts; {len(components)} components; {len(ranges)} Unicode ranges.\n'
    'Generated by Doroti/eng/generate-font-fallbacks.py. See LICENSE.flutter.txt.\n', encoding='utf-8')
print(f'{len(fonts)} fonts, {len(components)} components, {len(ranges)} ranges')
