#Requires -Version 5.1
param(
    [Parameter(Mandatory = $true)]
    [string] $CandidateRoot
)

$ErrorActionPreference = 'Stop'
$dorotiRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$CandidateRoot = (Resolve-Path $CandidateRoot).Path
$candidateProject = Join-Path $CandidateRoot 'projects/Widgets'
$reportPath = Join-Path $CandidateRoot 'converter-report.json'
$coveragePath = Join-Path $CandidateRoot 'framework-coverage.json'
$selectionPath = Join-Path $dorotiRoot 'migration/selections/g5-3-widgets.json'
$closurePath = Join-Path $dorotiRoot 'migration/flutter-framework/f3-closure.json'
$targetRoot = Join-Path $dorotiRoot 'src/Doroti.Framework.Widgets'
$manifestRoot = Join-Path $dorotiRoot 'migration/flutter-framework'
$revision = '56b8e1a851a594b1a154f8ea93270807dab22b9a'

function Write-Utf8Lf {
    param([string] $Path, [string] $Content)
    $normalized = $Content -replace "`r`n", "`n"
    if (-not $normalized.EndsWith("`n", [StringComparison]::Ordinal)) { $normalized += "`n" }
    [IO.File]::WriteAllText($Path, $normalized, [Text.UTF8Encoding]::new($false))
}

foreach ($required in @($reportPath, $coveragePath, $selectionPath, $closurePath)) {
    if (-not (Test-Path -LiteralPath $required -PathType Leaf)) { throw "G5-3 promotion input is missing: $required" }
}
if (-not (Test-Path -LiteralPath $candidateProject -PathType Container)) {
    throw "G5-3 Widgets candidate project is missing: $candidateProject"
}

$report = Get-Content -LiteralPath $reportPath -Raw | ConvertFrom-Json
$coverage = Get-Content -LiteralPath $coveragePath -Raw | ConvertFrom-Json
$selection = Get-Content -LiteralPath $selectionPath -Raw | ConvertFrom-Json
$closure = Get-Content -LiteralPath $closurePath -Raw | ConvertFrom-Json
$candidateErrors = @($report.diagnostics | Where-Object { $_.severity -eq 'error' })
if (-not $report.success -or @($report.outputs).Count -ne 185 -or
    $candidateErrors.Count -ne 0 -or $coverage.unclassifiedAstNodeCount -ne 0 -or
    $coverage.silentOmissionCount -ne 0 -or $coverage.generatedCompileErrorCount -ne 0) {
    throw 'G5-3 promotion requires a clean 185-file compiler candidate.'
}

$widgetInputs = @($selection.inputs | Where-Object { $_.library -match '^package:flutter/src/widgets/' })
$selectedDeclarations = @($widgetInputs | ForEach-Object { @($_.symbols) }).Count
if ($widgetInputs.Count -ne 186 -or $selectedDeclarations -ne 1715) {
    throw "G5-3 selection drifted: expected 186 libraries/1715 declarations, got $($widgetInputs.Count)/$selectedDeclarations."
}

[IO.Directory]::CreateDirectory($targetRoot) | Out-Null
Get-ChildItem -LiteralPath $targetRoot -File -Filter '*.cs' -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -ne 'ProductAssemblyMarker.cs' } |
    Remove-Item -Force

$reviewedSources = [Collections.Generic.List[string]]::new()
foreach ($source in Get-ChildItem -LiteralPath $candidateProject -File -Filter '*.g.cs' | Sort-Object Name) {
    $targetName = $source.Name -replace '\.g\.cs$', '.cs'
    $target = Join-Path $targetRoot $targetName
    $content = Get-Content -LiteralPath $source.FullName -Raw
    $sourceMatch = [regex]::Match($content, '(?m)^// Doroti typed semantic compiler .+; source: (?<source>.+)$')
    $flutterSource = if ($sourceMatch.Success) { $sourceMatch.Groups['source'].Value.Trim() } else { 'compiler-emitted support source' }
    $content = $content -replace '^// <auto-generated />\r?\n', "// <doroti-reviewed-framework-source />`n// Flutter $($revision.Substring(0, 8)): $flutterSource`n"
    $content = $content -replace '(?m)^// Doroti typed semantic compiler .+; source: .+\r?\n', ''
    Write-Utf8Lf -Path $target -Content $content
    $reviewedSources.Add("src/Doroti.Framework.Widgets/$targetName")
}

$outputByInput = @{}
foreach ($output in @($report.outputs)) {
    $relative = ([string]$output.input -replace '\\', '/')
    $marker = '/packages/flutter/lib/'
    $index = $relative.IndexOf($marker, [StringComparison]::Ordinal)
    if ($index -lt 0) { throw "Candidate output has an unexpected input path: $relative" }
    $libraryPath = $relative.Substring($index + $marker.Length)
    $outputByInput[$libraryPath] = $output
}

$widgetsRoot = $closure.libraries | Where-Object { $_.path -eq 'widgets.dart' } | Select-Object -First 1
$libraryByPath = @{}
foreach ($library in @($closure.libraries)) { $libraryByPath[[string]$library.path] = $library }
$exportedWidgetLibraries = @($widgetsRoot.dependencies | Where-Object { $_ -match '^src/widgets/' } | Sort-Object -Unique)
$apiEntries = [Collections.Generic.List[object]]::new()
$apiMissing = [Collections.Generic.List[object]]::new()
$apiExtra = [Collections.Generic.List[object]]::new()
foreach ($libraryPath in $exportedWidgetLibraries) {
    if (-not $libraryByPath.ContainsKey([string]$libraryPath)) { throw "widgets.dart export is absent from closure: $libraryPath" }
    $library = $libraryByPath[[string]$libraryPath]
    if (-not $outputByInput.ContainsKey([string]$libraryPath)) {
        if (@($library.declarations).Count -eq 0) { continue }
        throw "widgets.dart export is absent from candidate outputs: $libraryPath"
    }
    $actual = @($outputByInput[[string]$libraryPath].symbols | Where-Object { -not ([string]$_).StartsWith('_', [StringComparison]::Ordinal) })
    $expected = @($library.declarations | Where-Object { -not ([string]$_.name).StartsWith('_', [StringComparison]::Ordinal) })
    foreach ($declaration in $expected) {
        $entry = [ordered]@{
            library = "package:flutter/$libraryPath"
            name = [string]$declaration.name
            kind = [string]$declaration.kind
            elementId = [string]$declaration.canonicalElementId
            members = @($declaration.members | ForEach-Object { [string]$_ })
        }
        $apiEntries.Add($entry)
        if ($actual -notcontains $entry.name) { $apiMissing.Add($entry) }
    }
    foreach ($name in $actual | Where-Object { $_ -notin @($expected.name) }) {
        $apiExtra.Add([ordered]@{ library = "package:flutter/$libraryPath"; name = [string]$name })
    }
}

$boundaryByLibrary = @{}
foreach ($input in $widgetInputs) { $boundaryByLibrary[[string]$input.library] = @($input.boundarySymbols) }
$dispositionEntries = [Collections.Generic.List[object]]::new()
foreach ($input in $widgetInputs) {
    $libraryPath = ([string]$input.library).Substring('package:flutter/'.Length)
    $library = $libraryByPath[$libraryPath]
    foreach ($declaration in @($library.declarations)) {
        $isBoundary = @($boundaryByLibrary[[string]$input.library]) -contains [string]$declaration.name
        $dispositionEntries.Add([ordered]@{
            elementId = [string]$declaration.canonicalElementId
            library = [string]$input.library
            symbol = [string]$declaration.name
            declarationKind = [string]$declaration.kind
            disposition = if ($isBoundary) { 'exclude-with-owner' } else { 'promoted' }
            target = if ($isBoundary) { $null } else { "src/Doroti.Framework.Widgets/$([IO.Path]::GetFileNameWithoutExtension($libraryPath)).cs" }
            boundaryOwner = if ($isBoundary) { 'Doroti.Ui typed host capability' } else { $null }
            validationCase = 'g5-3-widgets-product'
        })
    }
}

$apiManifest = [ordered]@{
    schemaVersion = 'doroti.g5-3-widgets-api-manifest/v1'
    milestone = 'G5-3'
    upstreamRevision = $revision
    root = 'package:flutter/widgets.dart'
    exportedWidgetLibraries = $exportedWidgetLibraries
    declarationOccurrences = @($apiEntries | Sort-Object library, name, elementId)
    missing = @($apiMissing)
    extra = @($apiExtra)
    reviewedSources = @($reviewedSources)
    counts = [ordered]@{
        exportedWidgetLibraries = $exportedWidgetLibraries.Count
        declarationOccurrences = $apiEntries.Count
        uniqueDeclarationNames = @($apiEntries.name | Sort-Object -Unique).Count
        missing = $apiMissing.Count
        extra = $apiExtra.Count
    }
}
$disposition = [ordered]@{
    schemaVersion = 'doroti.g5-3-widgets-disposition/v1'
    milestone = 'G5-3'
    upstreamRevision = $revision
    entries = @($dispositionEntries | Sort-Object library, symbol, elementId)
    counts = [ordered]@{
        selectedDeclarations = $dispositionEntries.Count
        promoted = @($dispositionEntries | Where-Object disposition -eq 'promoted').Count
        excludeWithOwner = @($dispositionEntries | Where-Object disposition -eq 'exclude-with-owner').Count
        unowned = @($dispositionEntries | Where-Object { -not $_.disposition -or ($_.disposition -eq 'exclude-with-owner' -and -not $_.boundaryOwner) }).Count
    }
}
Write-Utf8Lf (Join-Path $manifestRoot 'g5-3-widgets-api-manifest.json') ($apiManifest | ConvertTo-Json -Depth 12)
Write-Utf8Lf (Join-Path $manifestRoot 'g5-3-widgets-disposition.json') ($disposition | ConvertTo-Json -Depth 12)

if ($apiMissing.Count -ne 0 -or $apiExtra.Count -ne 0 -or $dispositionEntries.Count -ne 1715 -or $disposition.counts.unowned -ne 0) {
    throw "G5-3 product review is incomplete: missing=$($apiMissing.Count), extra=$($apiExtra.Count), disposition=$($dispositionEntries.Count), unowned=$($disposition.counts.unowned)."
}

Write-Output "G5-3 Widgets promotion: PASS (185 libraries, 1715 declarations, $($apiEntries.Count) widgets.dart public declarations)"
Write-Output "Product: $targetRoot"
