#Requires -Version 5.1
param(
    [string] $CandidateRoot
)

$ErrorActionPreference = 'Stop'
$dorotiRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$repositoryRoot = (Resolve-Path (Join-Path $dorotiRoot '..')).Path
$revision = '56b8e1a851a594b1a154f8ea93270807dab22b9a'
if ([string]::IsNullOrWhiteSpace($CandidateRoot)) {
    $CandidateRoot = Join-Path $dorotiRoot "migration/generated-candidates/flutter-framework/$revision/g4-4"
}
$CandidateRoot = (Resolve-Path $CandidateRoot).Path

$report = Get-Content (Join-Path $CandidateRoot 'converter-report.json') -Raw | ConvertFrom-Json
$coverage = Get-Content (Join-Path $CandidateRoot 'framework-coverage.json') -Raw | ConvertFrom-Json
$migrationIr = Get-Content (Join-Path $CandidateRoot 'migration-ir.json') -Raw | ConvertFrom-Json
if (-not $report.success -or @($report.outputs).Count -ne 42) {
    throw 'G4-4 promotion requires a successful 42-output compiler report.'
}
if ($coverage.declarationCount -ne 353 -or $coverage.memberCount -ne 1709 -or
    $coverage.unclassifiedAstNodeCount -ne 0 -or $coverage.silentOmissionCount -ne 0 -or
    $coverage.generatedCompileErrorCount -ne 0) {
    throw 'G4-4 promotion requires the closed 353-declaration/1709-member compiler census.'
}

function Write-Utf8Lf {
    param([string] $Path, [string] $Content)
    $normalized = ($Content -replace "`r`n", "`n")
    if (-not $normalized.EndsWith("`n", [StringComparison]::Ordinal)) {
        $normalized += "`n"
    }
    [IO.File]::WriteAllText($Path, $normalized, [Text.UTF8Encoding]::new($false))
}

function Get-ProjectName {
    param([string] $Library)
    if ($Library -match '/src/(physics|animation|gestures)/') {
        return [Globalization.CultureInfo]::InvariantCulture.TextInfo.ToTitleCase($Matches[1])
    }
    throw "G4-4 library is outside the promotion boundary: $Library"
}

$projectTargets = [ordered]@{
    Physics = Join-Path $dorotiRoot 'src/Doroti.Framework.Physics'
    Animation = Join-Path $dorotiRoot 'src/Doroti.Framework.Animation'
    Gestures = Join-Path $dorotiRoot 'src/Doroti.Framework.Gestures'
}

foreach ($project in $projectTargets.Keys) {
    $sourceRoot = Join-Path $CandidateRoot "projects/$project"
    $targetRoot = $projectTargets[$project]
    New-Item -ItemType Directory -Force -Path $targetRoot | Out-Null
    foreach ($source in Get-ChildItem $sourceRoot -File -Filter '*.g.cs') {
        $targetName = $source.Name -replace '\.g\.cs$', '.cs'
        $target = Join-Path $targetRoot $targetName
        # Tolerance was already reviewed and promoted by G3-2. G4-4 owns the
        # wider Physics surface but must not overwrite that earlier review.
        if ($project -eq 'Physics' -and $targetName -eq 'tolerance.cs' -and (Test-Path $target)) {
            continue
        }
        $content = Get-Content $source.FullName -Raw
        if ($source.Name -notlike '*GlobalUsings.g.cs') {
            $relativeFlutterSource = [regex]::Match($content, 'source: \.\./\.\./\.\./reference/flutter-master/(.+)$', 'Multiline').Groups[1].Value.Trim()
            if ([string]::IsNullOrWhiteSpace($relativeFlutterSource)) {
                throw "Candidate source metadata is missing: $($source.FullName)"
            }
            $content = $content -replace '^// <auto-generated />\r?\n', "// <doroti-reviewed-framework-source />`n// Flutter 56b8e1a8: $relativeFlutterSource`n"
            $content = $content -replace '(?m)^// Doroti typed semantic compiler .+; source: .+\r?\n', ''
        }
        Write-Utf8Lf -Path $target -Content $content
    }
}

# Product policy: velocity tracking must remain usable by headless/external
# recognizer adapters before a GestureBinding has been initialized.
$velocityTrackerPath = Join-Path $projectTargets.Gestures 'velocity_tracker.cs'
$velocityTracker = Get-Content $velocityTrackerPath -Raw
$bindingClock = '_stopwatch ??= GestureBinding.instance.samplingClock.stopwatch();'
$fallbackClock = '_stopwatch ??= GestureBinding._instance?.samplingClock.stopwatch() ?? new Stopwatch();'
if ($velocityTracker.IndexOf($bindingClock, [StringComparison]::Ordinal) -lt 0) {
    throw 'G4-4 velocity tracker promotion no longer exposes the expected GestureBinding clock call.'
}
Write-Utf8Lf -Path $velocityTrackerPath -Content $velocityTracker.Replace($bindingClock, $fallbackClock)

$dispositionEntries = [Collections.Generic.List[object]]::new()
$publicDeclarations = [Collections.Generic.List[object]]::new()
$publicMembers = [Collections.Generic.List[object]]::new()
foreach ($input in @($migrationIr.inputs)) {
    $project = Get-ProjectName $input.library
    $sourcePath = [IO.Path]::GetFileName($input.path)
    $target = "src/Doroti.Framework.$project/$([IO.Path]::GetFileNameWithoutExtension($sourcePath)).cs"
    foreach ($declaration in @($input.declarations)) {
        $dispositionEntries.Add([ordered]@{
            elementId = $declaration.element.canonicalId
            sourcePath = $sourcePath
            symbol = $declaration.name
            declarationKind = $declaration.kind
            sourceOffset = $declaration.offset
            disposition = 'promoted'
            target = $target
            capabilityId = $null
            validationCase = 'g4-4-promotion-api'
        })
        if (-not $declaration.element.isPrivate) {
            $publicDeclarations.Add([ordered]@{
                library = $input.library
                name = $declaration.name
                kind = $declaration.kind
                elementId = $declaration.element.canonicalId
                sourceOffset = $declaration.offset
                type = $declaration.element.type
                returnType = $declaration.element.returnType
            })
            foreach ($member in @($declaration.members)) {
                if ($member.element.isPrivate) { continue }
                $parameters = @($member.element.parameters | ForEach-Object {
                    [ordered]@{
                        name = $_.name
                        type = $_.type
                        kind = $_.kind
                        isInitializingFormal = [bool]$_.isInitializingFormal
                        isSuperFormal = [bool]$_.isSuperFormal
                    }
                })
                $publicMembers.Add([ordered]@{
                    library = $input.library
                    owner = $declaration.name
                    name = $member.name
                    kind = $member.kind
                    elementId = $member.element.canonicalId
                    isStatic = [bool]$member.isStatic
                    type = $member.element.type
                    returnType = $member.element.returnType
                    parameters = $parameters
                })
            }
        }
    }
}

$manifestRoot = Join-Path $dorotiRoot 'migration/flutter-framework'
$disposition = [ordered]@{
    schemaVersion = 'doroti.g4-4-physics-animation-gestures-disposition/v1'
    milestone = 'G4-4'
    upstreamRevision = $revision
    entries = @($dispositionEntries | Sort-Object elementId, sourceOffset)
}
$uniquePublicDeclarationNames = @($publicDeclarations |
    ForEach-Object { [string]$_['name'] } |
    Sort-Object -Unique)
$apiManifest = [ordered]@{
    schemaVersion = 'doroti.g4-4-api-manifest/v1'
    milestone = 'G4-4'
    upstreamRevision = $revision
    declarationOccurrences = @($publicDeclarations | Sort-Object library, sourceOffset, elementId)
    uniquePublicDeclarationNames = $uniquePublicDeclarationNames
    publicMembers = @($publicMembers | Sort-Object library, owner, elementId)
    reviewedSources = @($projectTargets.Values | ForEach-Object {
        $targetRoot = $_
        Get-ChildItem $targetRoot -File -Filter '*.cs' |
            Where-Object { $_.FullName -notmatch '[\\/](bin|obj)[\\/]' } |
            ForEach-Object { $_.FullName.Substring($dorotiRoot.Length + 1).Replace('\', '/') }
    } | Sort-Object -Unique)
    counts = [ordered]@{
        declarationOccurrences = $publicDeclarations.Count
        uniqueDeclarationNames = $uniquePublicDeclarationNames.Count
        publicMembers = $publicMembers.Count
    }
}
Write-Utf8Lf (Join-Path $manifestRoot 'g4-4-physics-animation-gestures-disposition.json') (($disposition | ConvertTo-Json -Depth 12))
Write-Utf8Lf (Join-Path $manifestRoot 'g4-4-api-manifest.json') (($apiManifest | ConvertTo-Json -Depth 12))

Write-Output "G4-4 reviewed source promotion: PASS (42 libraries, $($dispositionEntries.Count) declarations, $($publicMembers.Count) public members)"
