#Requires -Version 5.1
param(
    [string] $CandidateRoot
)

$ErrorActionPreference = 'Stop'
$dorotiRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$revision = '56b8e1a851a594b1a154f8ea93270807dab22b9a'
if ([string]::IsNullOrWhiteSpace($CandidateRoot)) {
    $CandidateRoot = Join-Path $dorotiRoot "migration/generated-candidates/flutter-framework/$revision/g4-5"
}
$CandidateRoot = (Resolve-Path $CandidateRoot).Path

$report = Get-Content (Join-Path $CandidateRoot 'converter-report.json') -Raw | ConvertFrom-Json
$coverage = Get-Content (Join-Path $CandidateRoot 'framework-coverage.json') -Raw | ConvertFrom-Json
$migrationIr = Get-Content (Join-Path $CandidateRoot 'migration-ir.json') -Raw | ConvertFrom-Json
if (-not $report.success -or @($report.outputs).Count -ne 101) {
    throw 'G5-2 promotion requires a successful 101-output compiler report.'
}
if ($coverage.declarationCount -ne 663 -or $coverage.memberCount -ne 6206 -or
    $coverage.unclassifiedAstNodeCount -ne 0 -or $coverage.silentOmissionCount -ne 0 -or
    $coverage.generatedCompileErrorCount -ne 0) {
    throw 'G5-2 promotion requires the closed 663-declaration/6206-member compiler census.'
}

function Write-Utf8Lf {
    param([string] $Path, [string] $Content)
    $normalized = $Content -replace "`r`n", "`n"
    if (-not $normalized.EndsWith("`n", [StringComparison]::Ordinal)) { $normalized += "`n" }
    [IO.File]::WriteAllText($Path, $normalized, [Text.UTF8Encoding]::new($false))
}

function Get-Partition {
    param([string] $Library)
    if ($Library -match '/src/(painting|rendering|semantics)/') {
        return [Globalization.CultureInfo]::InvariantCulture.TextInfo.ToTitleCase($Matches[1])
    }
    throw "G5-2 library is outside the promotion boundary: $Library"
}

$projectTargets = [ordered]@{
    Painting = Join-Path $dorotiRoot 'src/Doroti.Framework.Painting'
    Semantics = Join-Path $dorotiRoot 'src/Doroti.Framework.Semantics'
    Rendering = Join-Path $dorotiRoot 'src/Doroti.Framework.Rendering'
}

foreach ($partition in $projectTargets.Keys) {
    $sourceRoot = Join-Path $CandidateRoot "projects/$partition"
    $targetRoot = $projectTargets[$partition]
    New-Item -ItemType Directory -Force -Path $targetRoot | Out-Null
    foreach ($source in Get-ChildItem $sourceRoot -File -Filter '*.g.cs') {
        $targetName = $source.Name -replace '\.g\.cs$', '.cs'
        $target = Join-Path $targetRoot $targetName
        $content = Get-Content $source.FullName -Raw
        if ($source.Name -notlike '*GlobalUsings.g.cs') {
            $relativeFlutterSource = [regex]::Match($content, 'source: \.\./\.\./\.\./reference/flutter-master/(.+)$', 'Multiline').Groups[1].Value.Trim()
            if ([string]::IsNullOrWhiteSpace($relativeFlutterSource)) {
                throw "Candidate source metadata is missing: $($source.FullName)"
            }
            $content = $content -replace '^// <auto-generated />\r?\n', "// <doroti-reviewed-framework-source />`n// Flutter 56b8e1a8: $relativeFlutterSource`n"
            $content = $content -replace '(?m)^// Doroti typed semantic compiler .+; source: .+\r?\n', ''
        }
        Write-Utf8Lf -Path $target -Content $content
    }
}

foreach ($partition in $projectTargets.Keys) {
    $projectPath = Join-Path $projectTargets[$partition] "Doroti.Framework.$partition.csproj"
    foreach ($pass in 1..2) {
        & dotnet format $projectPath --no-restore --verbosity quiet
        if ($LASTEXITCODE -ne 0) {
            throw "G5-2 reviewed source formatting pass $pass failed for $partition with exit code $LASTEXITCODE."
        }
    }
    & dotnet format $projectPath --verify-no-changes --no-restore --verbosity quiet
    if ($LASTEXITCODE -ne 0) {
        throw "G5-2 reviewed source formatting verification failed for $partition with exit code $LASTEXITCODE."
    }
}

$dispositionEntries = [Collections.Generic.List[object]]::new()
$publicDeclarations = [Collections.Generic.List[object]]::new()
$publicMembers = [Collections.Generic.List[object]]::new()
foreach ($input in @($migrationIr.inputs)) {
    $partition = Get-Partition $input.library
    $sourcePath = [IO.Path]::GetFileName($input.path)
    $target = "src/Doroti.Framework.$partition/$([IO.Path]::GetFileNameWithoutExtension($sourcePath)).cs"
    foreach ($declaration in @($input.declarations)) {
        $dispositionEntries.Add([ordered]@{
            elementId = $declaration.element.canonicalId
            library = $input.library
            sourcePath = $sourcePath
            symbol = $declaration.name
            declarationKind = $declaration.kind
            sourceOffset = $declaration.offset
            disposition = 'promoted'
            target = $target
            boundaryOwner = $null
            validationCase = 'g5-2-promotion-api'
        })
        if (-not $declaration.element.isPrivate) {
            $publicDeclarations.Add([ordered]@{
                library = $input.library
                name = $declaration.name
                kind = $declaration.kind
                elementId = $declaration.element.canonicalId
                sourceOffset = $declaration.offset
                type = $declaration.element.type
                returnType = $declaration.element.returnType
            })
            foreach ($member in @($declaration.members)) {
                if ($member.element.isPrivate) { continue }
                $publicMembers.Add([ordered]@{
                    library = $input.library
                    owner = $declaration.name
                    name = $member.name
                    kind = $member.kind
                    elementId = $member.element.canonicalId
                    isStatic = [bool]$member.isStatic
                    type = $member.element.type
                    returnType = $member.element.returnType
                    parameters = @($member.element.parameters | ForEach-Object {
                        [ordered]@{
                            name = $_.name
                            type = $_.type
                            kind = $_.kind
                            isInitializingFormal = [bool]$_.isInitializingFormal
                            isSuperFormal = [bool]$_.isSuperFormal
                        }
                    })
                })
            }
        }
    }
}

$manifestRoot = Join-Path $dorotiRoot 'migration/flutter-framework'
$disposition = [ordered]@{
    schemaVersion = 'doroti.g5-2-painting-rendering-semantics-disposition/v1'
    milestone = 'G5-2'
    upstreamRevision = $revision
    dependencyOrder = @('Painting', 'Semantics', 'Rendering')
    entries = @($dispositionEntries | Sort-Object elementId, sourceOffset)
}
$uniqueNames = @($publicDeclarations | ForEach-Object { [string]$_['name'] } | Sort-Object -Unique)
$apiManifest = [ordered]@{
    schemaVersion = 'doroti.g5-2-api-manifest/v1'
    milestone = 'G5-2'
    upstreamRevision = $revision
    declarationOccurrences = @($publicDeclarations | Sort-Object library, sourceOffset, elementId)
    uniquePublicDeclarationNames = $uniqueNames
    publicMembers = @($publicMembers | Sort-Object library, owner, elementId)
    reviewedSources = @($projectTargets.Values | ForEach-Object {
        $root = $_
        Get-ChildItem $root -File -Filter '*.cs' | ForEach-Object {
            $_.FullName.Substring($dorotiRoot.Length + 1).Replace('\', '/')
        }
    } | Sort-Object -Unique)
    counts = [ordered]@{
        selectedDeclarations = $dispositionEntries.Count
        declarationOccurrences = $publicDeclarations.Count
        uniqueDeclarationNames = $uniqueNames.Count
        publicMembers = $publicMembers.Count
    }
}
Write-Utf8Lf (Join-Path $manifestRoot 'g5-2-painting-rendering-semantics-disposition.json') ($disposition | ConvertTo-Json -Depth 12)
Write-Utf8Lf (Join-Path $manifestRoot 'g5-2-api-manifest.json') ($apiManifest | ConvertTo-Json -Depth 12)

Write-Output "G5-2 reviewed source promotion: PASS (101 libraries, $($dispositionEntries.Count) declarations, $($publicMembers.Count) public members)"
