#Requires -Version 5.1
param(
    [string] $ReviewedRoot,
    [ValidateSet('All', 'Material', 'Cupertino')]
    [string] $ProjectName = 'All'
)

$ErrorActionPreference = 'Stop'
$dorotiRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
if ([string]::IsNullOrWhiteSpace($ReviewedRoot)) {
    $reviewedRoot = Join-Path $dorotiRoot 'migration/generated-candidates/g5-4-reviewed/projects'
} elseif ([IO.Path]::IsPathRooted($ReviewedRoot)) {
    $reviewedRoot = [IO.Path]::GetFullPath($ReviewedRoot)
} else {
    $reviewedRoot = [IO.Path]::GetFullPath((Join-Path $dorotiRoot $ReviewedRoot))
}
$candidateBase = [IO.Path]::GetFullPath((Join-Path $dorotiRoot 'migration/generated-candidates'))
if (-not $reviewedRoot.StartsWith($candidateBase, [StringComparison]::OrdinalIgnoreCase)) {
    throw "Reviewed promotion source must remain under $candidateBase."
}
$artifactRoot = Join-Path $dorotiRoot 'artifacts/g6-material-demo'
$projects = @(
    [pscustomobject]@{ Name = 'Cupertino'; Target = 'Doroti.Flutter.Framework.Cupertino' },
    [pscustomobject]@{ Name = 'Material'; Target = 'Doroti.Flutter.Framework.Material' }
)
if ($ProjectName -ne 'All') { $projects = @($projects | Where-Object Name -eq $ProjectName) }

$entries = [Collections.Generic.List[object]]::new()
foreach ($project in $projects) {
    $sourceRoot = Join-Path $reviewedRoot $project.Name
    $targetRoot = Join-Path (Join-Path $dorotiRoot 'src') $project.Target
    if (-not (Test-Path -LiteralPath $sourceRoot -PathType Container)) {
        throw "Reviewed G5-4 source is missing: $sourceRoot"
    }
    if (-not (Test-Path -LiteralPath $targetRoot -PathType Container)) {
        New-Item -ItemType Directory -Path $targetRoot | Out-Null
    }
    $resolvedTarget = (Resolve-Path -LiteralPath $targetRoot).Path
    $expectedPrefix = (Resolve-Path -LiteralPath (Join-Path $dorotiRoot 'src')).Path + [IO.Path]::DirectorySeparatorChar
    if (-not $resolvedTarget.StartsWith($expectedPrefix, [StringComparison]::OrdinalIgnoreCase)) {
        throw "Promotion target escaped Doroti/src: $resolvedTarget"
    }
    Get-ChildItem -LiteralPath $resolvedTarget -File -Filter '*.cs' | Remove-Item -Force
    $names = [Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
    foreach ($source in Get-ChildItem -LiteralPath $sourceRoot -File -Filter '*.g.cs' | Sort-Object Name) {
        $destinationName = $source.Name -replace '(\.g)+\.cs$', '.cs'
        if (-not $names.Add($destinationName)) { throw "Promotion filename collision: $destinationName" }
        $destination = Join-Path $resolvedTarget $destinationName
        $text = [IO.File]::ReadAllText($source.FullName)
        $text = $text.Replace('// <auto-generated />', '// <doroti-reviewed-product-source milestone="G6-3" />')
        $text = $text.TrimEnd("`r", "`n") + "`n"
        [IO.File]::WriteAllText($destination, $text, [Text.UTF8Encoding]::new($false))
        $entries.Add([ordered]@{
            project = $project.Name
            source = $source.FullName.Substring($dorotiRoot.Length + 1).Replace('\', '/')
            product = $destination.Substring($dorotiRoot.Length + 1).Replace('\', '/')
            sha256 = (Get-FileHash -LiteralPath $destination -Algorithm SHA256).Hash.ToLowerInvariant()
        })
    }
}

New-Item -ItemType Directory -Path $artifactRoot -Force | Out-Null
$manifest = [ordered]@{
    schemaVersion = 'doroti.g6-material-product-promotion/v1'
    milestone = 'G6-3'
    source = [IO.Path]::GetRelativePath($dorotiRoot, $reviewedRoot).Replace('\', '/')
    destination = 'src'
    generatedFiles = $entries.Count
    files = $entries
}
$json = ($manifest | ConvertTo-Json -Depth 8) -replace "`r`n", "`n"
[IO.File]::WriteAllText((Join-Path $artifactRoot 'product-promotion.json'), $json + "`n", [Text.UTF8Encoding]::new($false))
Write-Output "G6-3 Material product promotion: PASS ($($entries.Count) files)"
