#Requires -Version 5.1
param(
    [ValidateSet('All', 'Compatibility', 'ManagedRegression', 'Product', 'FormatBaseline', 'Evidence', 'Build')]
    [string] $Shard = 'All'
)

$ErrorActionPreference = 'Stop'
$env:DOTNET_CLI_DO_NOT_USE_MSBUILD_SERVER = '1'
$env:MSBUILDDISABLENODEREUSE = '1'
$dorotiRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$repoRoot = (Resolve-Path (Join-Path $dorotiRoot '..')).Path
$migrationRoot = Join-Path $dorotiRoot 'migration/flutter-framework'
$targetRoot = Join-Path $dorotiRoot 'migration/targets'
$localRoot = Join-Path $dorotiRoot '.doroti/tmp/g7-baseline'
$compatibilityPath = Join-Path $migrationRoot 'g7-compatibility-debt.json'
$managedRegressionPath = Join-Path $migrationRoot 'g7-managed-regression.json'
$productSmokePath = Join-Path $migrationRoot 'g7-windows-product-smoke.json'
$formatBaselinePath = Join-Path $migrationRoot 'g7-format-baseline.json'
$carryoverPath = Join-Path $migrationRoot 'g7-carryover.json'
$targetMatrixPath = Join-Path $targetRoot 'g7-target-matrix.json'
$dorotiRevision = (& git -C $repoRoot rev-parse HEAD).Trim()
if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($dorotiRevision)) { throw 'Unable to resolve the Doroti repository revision.' }

function Test-Shard([string] $Name) { return $Shard -eq 'All' -or $Shard -eq $Name }

function Assert-True([bool] $Condition, [string] $Name) {
    if (-not $Condition) { throw "$Name failed." }
}

function Assert-Equal([object] $Actual, [object] $Expected, [string] $Name) {
    if ($Actual -ne $Expected) { throw "$Name drifted: expected '$Expected', got '$Actual'." }
}

function Invoke-Checked([scriptblock] $Command, [string] $Failure) {
    $global:LASTEXITCODE = 0
    & $Command | Out-Host
    if ($LASTEXITCODE -ne 0) { throw "$Failure (exit code $LASTEXITCODE)." }
}

function Write-Json([string] $Path, [object] $Value) {
    [IO.Directory]::CreateDirectory((Split-Path $Path -Parent)) | Out-Null
    $json = (($Value | ConvertTo-Json -Depth 64) -replace "`r`n", "`n") + "`n"
    [IO.File]::WriteAllText($Path, $json, [Text.UTF8Encoding]::new($false))
}

function Read-Json([string] $Path) {
    Assert-True (Test-Path -LiteralPath $Path -PathType Leaf) "Required evidence $Path"
    return Get-Content -LiteralPath $Path -Raw | ConvertFrom-Json
}

function Relative-Path([string] $Path) {
    return [IO.Path]::GetRelativePath($repoRoot, $Path).Replace('\', '/')
}

function Get-ProductDiffs {
    $rows = [Collections.Generic.List[object]]::new()
    foreach ($project in @('Material', 'Cupertino')) {
        $reviewedRoot = Join-Path $dorotiRoot "migration/generated-candidates/g5-4-reviewed/projects/$project"
        $productRoot = Join-Path $dorotiRoot "src/Doroti.Flutter.Framework.$project"
        foreach ($reviewed in Get-ChildItem -LiteralPath $reviewedRoot -File -Filter '*.g.cs') {
            $productName = $reviewed.Name -replace '(\.g)+\.cs$', '.cs'
            $product = Join-Path $productRoot $productName
            if (-not (Test-Path -LiteralPath $product -PathType Leaf)) { continue }
            $reviewedText = (([IO.File]::ReadAllText($reviewed.FullName) -replace '^// <auto-generated />', '// <doroti-reviewed-product-source milestone="G6-3" />') -replace '\bDotori\b', 'Doroti').TrimEnd("`r", "`n") + "`n"
            if ($reviewedText -ceq [IO.File]::ReadAllText($product)) { continue }
            $rows.Add([ordered]@{
                project = $project
                file = $productName
                reviewed = Relative-Path $reviewed.FullName
                product = Relative-Path $product
            })
        }
    }
    return @($rows)
}

function Invoke-CompatibilityShard {
    $reviewScript = Join-Path $dorotiRoot 'eng/review-g5-4-generated.ps1'
    $adaptationPath = Join-Path $dorotiRoot 'migration/generated-candidates/g5-4-reviewed/g5-4-reviewed-adaptations.json'
    $adaptations = Read-Json $adaptationPath
    $reviewLines = [IO.File]::ReadAllLines($reviewScript)
    $lowererPaths = @(Get-ChildItem (Join-Path $repoRoot 'tools/Doroti.DartToCSharp/src/Backend/CSharp/Lowering') -File -Filter 'FrameworkCSharpLowerer*.cs')

    $reviewRules = [Collections.Generic.List[object]]::new()
    $numericReviewRules = [Collections.Generic.List[object]]::new()
    $widgetSubstitutions = [Collections.Generic.List[object]]::new()
    for ($index = 0; $index -lt $reviewLines.Length; $index++) {
        $lineNumber = $index + 1
        $line = $reviewLines[$index]
        if ($line -match '^\s*Update-GeneratedFile\b') {
            $reviewRules.Add([ordered]@{ path=Relative-Path $reviewScript; line=$lineNumber })
        }
        if ($line -match '(?:__|counter__)\d+') {
            $numericReviewRules.Add([ordered]@{ path=Relative-Path $reviewScript; line=$lineNumber })
        }
        if ($line -match 'Ink[^\r\n]*DecoratedBox|DecoratedBox[^\r\n]*Ink') {
            $widgetSubstitutions.Add([ordered]@{ path=Relative-Path $reviewScript; line=$lineNumber })
        }
    }

    $lowererRewrites = [Collections.Generic.List[object]]::new()
    $numericLowererRules = [Collections.Generic.List[object]]::new()
    foreach ($path in $lowererPaths) {
        $lines = [IO.File]::ReadAllLines($path.FullName)
        for ($index = 0; $index -lt $lines.Length; $index++) {
            $line = $lines[$index]
            if ($line -notmatch '(?:source\s*=\s*)?(?:source\.)?Replace\(|Regex\.Replace\(source|source\s*=\s*source') { continue }
            $row = [ordered]@{ path=Relative-Path $path.FullName; line=$index + 1 }
            $lowererRewrites.Add($row)
            if ($line -match '(?:__|counter__)\d+') { $numericLowererRules.Add($row) }
        }
    }

    $unstagedGeneratedFiles = @(& git -C $repoRoot diff --name-only -- '*.g.cs')
    Assert-Equal $LASTEXITCODE 0 'Unstaged generated-file query'
    $stagedGeneratedFiles = @(& git -C $repoRoot diff --cached --name-only -- '*.g.cs')
    Assert-Equal $LASTEXITCODE 0 'Staged generated-file query'
    $untrackedGeneratedFiles = @(& git -C $repoRoot ls-files --others --exclude-standard -- '*.g.cs')
    Assert-Equal $LASTEXITCODE 0 'Untracked generated-file query'
    $worktreeGeneratedFiles = @($unstagedGeneratedFiles + $stagedGeneratedFiles + $untrackedGeneratedFiles) |
        Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
        Sort-Object -Unique
    $productDiffs = @(Get-ProductDiffs)
    $numericCount = $numericReviewRules.Count + $numericLowererRules.Count
    $blockingCount = 0
    foreach ($count in @([int]$adaptations.changedFiles, $numericCount, $widgetSubstitutions.Count, $productDiffs.Count, $worktreeGeneratedFiles.Count)) {
        if ($count -gt 0) { $blockingCount++ }
    }

    Write-Json $compatibilityPath ([ordered]@{
        schemaVersion = 'doroti.g7-compatibility-debt/v1'
        milestone = 'G7-0'
        status = $(if ($blockingCount -eq 0) { 'pass' } else { 'release-blocker-open' })
        aggregationPolicy = 'Signals overlap and are not summed into a synthetic total.'
        sourceQueries = @(
            [ordered]@{ id='worktree-generated-file-edit'; selector='git diff and git ls-files for modified, staged, or untracked *.g.cs'; source='current worktree and index' },
            [ordered]@{ id='reviewed-generated-adaptation'; selector='changedFiles and changes'; source=Relative-Path $adaptationPath },
            [ordered]@{ id='review-rewrite-rule'; selector='Update-GeneratedFile invocation'; source=Relative-Path $reviewScript },
            [ordered]@{ id='numeric-generated-local'; selector='(?:__|counter__) followed by digits'; source=@(Relative-Path $reviewScript; 'tools/Doroti.DartToCSharp/src/Backend/CSharp/Lowering/FrameworkCSharpLowerer*.cs') },
            [ordered]@{ id='widget-type-substitution'; selector='Ink and DecoratedBox substitution on one review-script line'; source=Relative-Path $reviewScript },
            [ordered]@{ id='promoted-product-direct-diff'; selector='reviewed generated source differs from promoted Material/Cupertino product source after the allowed Dotori-to-Doroti namespace normalization'; source='reviewed candidate and promoted product trees' }
        )
        forbiddenPatterns = [ordered]@{
            worktreeGeneratedFileEdits = [ordered]@{ count=$worktreeGeneratedFiles.Count; status=$(if ($worktreeGeneratedFiles.Count -eq 0) {'pass'} else {'open'}); matches=$worktreeGeneratedFiles }
            reviewedGeneratedAdaptations = [ordered]@{ count=[int]$adaptations.changedFiles; status=$(if ([int]$adaptations.changedFiles -eq 0) {'pass'} else {'open'}); owner='Doroti DartToCSharp compiler'; followUpMilestone='G7-1V' }
            numericGeneratedLocalDependencies = [ordered]@{ count=$numericCount; review=$numericReviewRules.Count; lowerer=$numericLowererRules.Count; status=$(if ($numericCount -eq 0) {'pass'} else {'open'}); owner='typed IR and common lowering'; followUpMilestone='G7-1V' }
            widgetTypeSubstitutions = [ordered]@{ count=$widgetSubstitutions.Count; status=$(if ($widgetSubstitutions.Count -eq 0) {'pass'} else {'open'}); owner='Flutter framework source semantics'; followUpMilestone='G7-1V' }
            promotedProductDirectDiffs = [ordered]@{ count=$productDiffs.Count; status=$(if ($productDiffs.Count -eq 0) {'pass'} else {'open'}); owner='Doroti framework promotion'; followUpMilestone='G7-1V'; matches=$productDiffs }
        }
        informational = [ordered]@{
            reviewRewriteRules = $reviewRules.Count
            lowererSourceRewriteRules = $lowererRewrites.Count
            reviewedAdaptationEntries = @($adaptations.changes).Count
        }
        reproduction = [ordered]@{
            command = 'Doroti/eng/validate-g7-baseline.ps1 -Shard Compatibility'
            maxMinutes = 20
        }
    })

    Assert-Equal $worktreeGeneratedFiles.Count 0 'Direct generated .g.cs worktree hotfixes'
    Write-Output "G7-0 compatibility query: PASS (review adaptations=$([int]$adaptations.changedFiles), numeric local dependencies=$numericCount, direct .g.cs edits=0, widget substitutions=$($widgetSubstitutions.Count), product diffs=$($productDiffs.Count); open debt retained for G7-1V)"
}

function Invoke-ManagedRegressionShard {
    $project = Join-Path $dorotiRoot 'validation/Doroti.Validation.G5Widgets/Doroti.Validation.G5Widgets.csproj'
    Invoke-Checked {
        dotnet run --project $project --configuration Release --no-restore -- --g7-focus-frame-dispatch-probe $managedRegressionPath
    } 'G7-0 managed focus/frame-dispatch regression probe failed'
    $evidence = Read-Json $managedRegressionPath
    Assert-Equal $evidence.schemaVersion 'doroti.g7-managed-regression/v1' 'Managed regression schema'
    Assert-Equal $evidence.status 'reproduced-release-blocker' 'Managed regression state'
    Assert-Equal $evidence.actual.capabilityId 'view.frame-dispatch' 'Managed regression capability'
    Assert-Equal ([long]$evidence.actual.viewId) 533 'Managed regression view'
    Assert-Equal $evidence.followUpMilestone 'G7-1C' 'Managed regression owner milestone'
    Write-Output 'G7-0 managed focus/frame-dispatch blocker taxonomy: PASS (minimal expected-failure probe reproduced)'
}

function Invoke-ProductShard {
    if ($env:OS -ne 'Windows_NT') { throw 'G7-0 Windows product smoke requires Windows.' }
    [IO.Directory]::CreateDirectory($localRoot) | Out-Null
    $demoProject = Join-Path $repoRoot 'DorotiDemoApp/DorotiDemoApp.csproj'
    $demoDll = Join-Path $repoRoot 'DorotiDemoApp/bin/Release/net10.0/DorotiDemoApp.dll'
    $rawEvidencePath = Join-Path $localRoot 'windows-product-smoke-raw.json'
    $artifactRoot = Join-Path $localRoot 'windows-product-smoke'
    Invoke-Checked {
        dotnet build $demoProject --configuration Release --nologo --disable-build-servers --tl:off -nodeReuse:false
    } 'G7-0 representative Windows product build failed'
    Invoke-Checked {
        dotnet $demoDll --smoke --entry home --frames 3 --duration-ms 15000 --cadence-duration-ms 0 --evidence $rawEvidencePath --artifact-dir $artifactRoot
    } 'G7-0 representative Windows product smoke failed'
    $raw = Read-Json $rawEvidencePath
    Assert-Equal $raw.outcome 'presented' 'Windows product outcome'
    Assert-Equal $raw.backend 'skia-wgl-opengl-gpu' 'Windows product backend'
    Assert-True ([long]$raw.frame.presented -ge 3) 'Windows product presented frames'
    Assert-Equal ([long]$raw.frame.failed) 0 'Windows product failed frames'
    Assert-Equal ([long]$raw.frame.cancelled) 0 'Windows product cancelled frames'
    Assert-Equal ([bool]$raw.frame.softwareFallbackUsed) $false 'Windows product software fallback'
    Assert-True ([long]$raw.interaction.nativePointerCount -ge 1) 'Windows product native pointer trace'
    Assert-True ([long]$raw.interaction.changedPixelCount -gt 0) 'Windows product state/raster change'
    Assert-Equal ([bool]$raw.resourceClosure.isBalanced) $true 'Windows product resource closure'

    Write-Json $productSmokePath ([ordered]@{
        schemaVersion = 'doroti.g7-windows-product-smoke/v1'
        milestone = 'G7-0'
        capturedAtUtc = [DateTimeOffset]::UtcNow
        status = 'verified-windows-x64-strict-gpu'
        fixture = [ordered]@{
            source = 'DorotiDemoApp/Program.cs'
            entry = 'home'
            selectionReason = 'smallest current promoted Material product path that crosses actual HWND, GPU present, native pointer, widget state/raster change, and resource closure'
            capabilities = @('gpu-first-frame', 'native-pointer', 'widget-state', 'raster-change', 'resource-closure')
        }
        result = [ordered]@{
            backend = [string]$raw.backend
            presented = [long]$raw.frame.presented
            failed = [long]$raw.frame.failed
            cancelled = [long]$raw.frame.cancelled
            softwareFallback = [bool]$raw.frame.softwareFallbackUsed
            nativePointerCount = [long]$raw.interaction.nativePointerCount
            changedPixelCount = [long]$raw.interaction.changedPixelCount
            resourceClosure = $raw.resourceClosure
        }
        boundaries = [ordered]@{
            generatedDartPackage = 'verified-predecessor-separate-g6-generated-demo-evidence'
            physicalInput = 'notVerified'
            browserWasm = 'notVerified'
        }
        reproduction = [ordered]@{ command='Doroti/eng/validate-g7-baseline.ps1 -Shard Product'; maxMinutes=20 }
    })
    Write-Output 'G7-0 representative Windows product smoke: PASS'
}

function Invoke-FormatBaselineShard {
    [IO.Directory]::CreateDirectory($localRoot) | Out-Null
    $stdoutPath = Join-Path $localRoot 'format-baseline.stdout.log'
    $stderrPath = Join-Path $localRoot 'format-baseline.stderr.log'
    $arguments = @('format', (Join-Path $dorotiRoot 'Doroti.slnx'), '--verify-no-changes', '--no-restore', '--verbosity', 'minimal')
    $process = Start-Process dotnet -ArgumentList $arguments -PassThru -NoNewWindow -RedirectStandardOutput $stdoutPath -RedirectStandardError $stderrPath
    if (-not $process.WaitForExit(1200000)) {
        $process.Kill($true)
        throw 'G7-0 format baseline exceeded the 20 minute shard limit.'
    }
    $output = @(
        Get-Content -LiteralPath $stdoutPath -ErrorAction SilentlyContinue
        Get-Content -LiteralPath $stderrPath -ErrorAction SilentlyContinue
    )
    $diagnostics = @($output | Where-Object { $_ -match ': error [A-Z]+' })
    Assert-True ($process.ExitCode -ne 0) 'Current full-solution format baseline must remain an explicit open blocker until repaired'
    Assert-True ($diagnostics.Count -gt 0) 'Full-solution format baseline diagnostics'
    $representative = @($diagnostics | Select-Object -First 10 | ForEach-Object { ([string]$_).Replace($repoRoot, '<repo>') })
    Write-Json $formatBaselinePath ([ordered]@{
        schemaVersion = 'doroti.g7-format-baseline/v1'
        milestone = 'G7-0'
        capturedAtUtc = [DateTimeOffset]::UtcNow
        status = 'reproduced-release-blocker'
        command = 'dotnet format Doroti/Doroti.slnx --verify-no-changes --no-restore --verbosity minimal'
        exitCode = $process.ExitCode
        diagnosticCount = $diagnostics.Count
        representativeDiagnostics = $representative
        owner = 'source owners of the committed formatting baseline'
        followUpMilestone = 'G7-1 before integrated release'
        mutationPolicy = 'G7-0 records the baseline and does not bulk-format unrelated committed source.'
        maxMinutes = 20
    })
    Write-Output "G7-0 full-solution format baseline: PASS (expected blocker reproduced; $($diagnostics.Count) diagnostics recorded without bulk mutation)"
}

function New-ReleaseBlocker(
    [string] $Id,
    [string] $State,
    [string] $Owner,
    [string] $Milestone,
    [string] $Command,
    [string] $Evidence
) {
    return [ordered]@{
        id = $Id
        state = $State
        owner = $Owner
        followUpMilestone = $Milestone
        reproduction = [ordered]@{ command=$Command; maxMinutes=20 }
        evidence = $Evidence
    }
}

function Invoke-EvidenceShard {
    $widgets = Read-Json (Join-Path $migrationRoot 'g6-widgets-live-evidence.json')
    $materialDemo = Read-Json (Join-Path $migrationRoot 'g6-material-demo-evidence.json')
    $appSlices = Read-Json (Join-Path $migrationRoot 'g6-app-slices.json')
    $materialMatrix = Read-Json (Join-Path $migrationRoot 'g6-material-component-matrix.json')
    $materialVisual = Read-Json (Join-Path $migrationRoot 'g6-material-visual-differential.json')
    $pointer = Read-Json (Join-Path $migrationRoot 'g6-pointer-interaction-evidence.json')
    $compositing = Read-Json (Join-Path $migrationRoot 'g6-compositing-effects-evidence.json')
    $cupertino = Read-Json (Join-Path $migrationRoot 'g6-cupertino-component-matrix.json')
    $generated = Read-Json (Join-Path $migrationRoot 'g6-generated-demo-evidence.json')
    $compatibility = Read-Json $compatibilityPath
    $managed = Read-Json $managedRegressionPath
    $product = Read-Json $productSmokePath
    $formatBaseline = Read-Json $formatBaselinePath

    Assert-Equal $widgets.status 'verified-windows-x64-strict-gpu' 'G6 Widgets predecessor'
    Assert-Equal $materialDemo.status 'verified-windows-x64-strict-gpu' 'G6 Material predecessor'
    Assert-Equal $appSlices.status 'verified-windows-x64-strict-gpu' 'G6 app slices predecessor'
    Assert-Equal ([long]$materialMatrix.counts.presented) 54 'G6 Material presented count'
    Assert-Equal ([long]$materialMatrix.counts.interactiveTested) 1 'G6 native input verified count'
    Assert-Equal $materialVisual.status 'notVerified' 'G6 Material reference boundary'
    Assert-Equal $pointer.status 'verified-windows-x64-strict-gpu-native-input' 'G6 pointer predecessor'
    Assert-Equal $compositing.status 'verified-windows-x64-strict-gpu-c0-partial' 'G6 compositing predecessor'
    Assert-Equal ([long]$cupertino.counts.presented) 55 'G6 Cupertino presented count'
    Assert-Equal $generated.status 'partial-prerequisites-and-differential-open' 'G6 generated product boundary'
    Assert-Equal $compatibility.status 'release-blocker-open' 'Compatibility debt boundary'
    Assert-Equal $managed.status 'reproduced-release-blocker' 'Managed regression boundary'
    Assert-Equal $product.status 'verified-windows-x64-strict-gpu' 'Current product smoke'
    Assert-Equal $formatBaseline.status 'reproduced-release-blocker' 'Full-solution format boundary'

    $webTargetPath = Join-Path $dorotiRoot 'src/Doroti.Target.Web.browser-wasm'
    $webHostPath = Join-Path $dorotiRoot 'src/Doroti.Host.Web'
    $webSourcePresent = (Test-Path -LiteralPath $webTargetPath -PathType Container) -and (Test-Path -LiteralPath $webHostPath -PathType Container)
    Write-Json $targetMatrixPath ([ordered]@{
        schemaVersion = 'doroti.g7-target-matrix/v1'
        milestone = 'G7-0'
        requiredTargets = @('win-x64', 'browser-wasm')
        targets = @(
            [ordered]@{
                id = 'win-x64'; requiredForGoal7=$true; host='Win32 window'; backend='skia-wgl-opengl-gpu'
                source='implemented'; build='verified-predecessor'; packaged='verified-predecessor'; live='verified-current-product-smoke'
                input='partial-capability-gate-open'; semantics='verified-predecessor-minimum'; physical='notVerified'; followUpMilestones=@('G7-1I','G7-5','G7-6')
            },
            [ordered]@{
                id = 'browser-wasm'; requiredForGoal7=$true; host='browser document and canvas'; backend='browser-gpu-required'
                source=$(if ($webSourcePresent) {'present-unverified'} else {'absent'}); build='notVerified'; packaged='notVerified'; live='notVerified'
                input='notVerified'; semantics='notVerified'; physical='notVerified'; followUpMilestones=@('G7-3','G7-4','G7-5','G7-6')
            }
        )
        deferred = @(
            [ordered]@{ id='linux-desktop'; requiredForGoal7=$false; status='notVerified'; promotionRule='becomes blocking only when selected as a supported release target' },
            [ordered]@{ id='macos-desktop'; requiredForGoal7=$false; status='notVerified'; promotionRule='becomes blocking only when selected as a supported release target' },
            [ordered]@{ id='firefox'; requiredForGoal7=$false; status='notVerified'; promotionRule='becomes blocking only when selected as a supported browser' },
            [ordered]@{ id='webkit'; requiredForGoal7=$false; status='notVerified'; promotionRule='becomes blocking only when selected as a supported browser' }
        )
        inferencePolicy = 'No PASS is transferred across target, backend, browser, automation, or physical boundaries.'
    })

    $blockers = @(
        (New-ReleaseBlocker 'material-reference-and-generation' 'open' 'compiler/lowerer and Material fidelity' 'G7-1V' 'Doroti/eng/validate-g6-material-fidelity.ps1 -Shard Visual' 'g6-material-visual-differential.json and g7-compatibility-debt.json'),
        (New-ReleaseBlocker 'windows-input-capabilities' 'open' 'Windows host input and shared gesture/semantics pipeline' 'G7-1I' 'Doroti/eng/validate-g6-pointer-interaction.ps1' 'g6-pointer-interaction-evidence.json'),
        (New-ReleaseBlocker 'managed-focus-frame-dispatch' 'open' 'managed view bootstrap and per-view frame dispatcher' 'G7-1C' 'Doroti/eng/validate-g7-baseline.ps1 -Shard ManagedRegression' 'g7-managed-regression.json'),
        (New-ReleaseBlocker 'compositing-reference-retained-c1' 'open' 'scene/raster retained effect pipeline' 'G7-1C' 'Doroti/eng/validate-g6-compositing-effects.ps1 -Shard Evidence' 'g6-compositing-effects-evidence.json'),
        (New-ReleaseBlocker 'cupertino-adaptive-generated-parity' 'open' 'Cupertino/adaptive framework and Dart application compiler' 'G7-2' 'Doroti/eng/validate-g7-baseline.ps1 -Shard Evidence' 'g6-cupertino-component-matrix.json and g6-generated-demo-evidence.json'),
        (New-ReleaseBlocker 'browser-wasm-build-live' $(if ($webSourcePresent) {'notVerified'} else {'absent'}) 'browser target/host and shared framework adapters' 'G7-3/G7-4' 'Doroti/eng/validate-g7-baseline.ps1 -Shard Evidence' 'g7-target-matrix.json'),
        (New-ReleaseBlocker 'solution-format-baseline' 'open' 'source owners of the committed formatting baseline' 'G7-1 before integrated release' 'Doroti/eng/validate-g7-baseline.ps1 -Shard FormatBaseline' 'g7-format-baseline.json'),
        (New-ReleaseBlocker 'integrated-release-stability' 'notVerified' 'Windows/Web release pipeline' 'G7-5' 'Doroti/eng/validate-g7-baseline.ps1 -Shard Evidence' 'g7-target-matrix.json'),
        (New-ReleaseBlocker 'physical-release-acceptance' 'notVerified' 'release acceptance' 'G7-6' 'Doroti/eng/validate-g7-baseline.ps1 -Shard Evidence' 'g7-target-matrix.json')
    )
    $invalidPasses = @($blockers | Where-Object { $_.state -match '^(PASS|pass|verified)' }).Count
    Assert-Equal $invalidPasses 0 'Stale PASS included in active release blockers'
    $missingMetadata = @($blockers | Where-Object {
        [string]::IsNullOrWhiteSpace($_.owner) -or [string]::IsNullOrWhiteSpace($_.followUpMilestone) -or
        [string]::IsNullOrWhiteSpace($_.reproduction.command) -or [string]::IsNullOrWhiteSpace($_.evidence)
    }).Count
    Assert-Equal $missingMetadata 0 'Release blocker metadata omissions'

    Write-Json $carryoverPath ([ordered]@{
        schemaVersion = 'doroti.g7-carryover/v1'
        milestone = 'G7-0'
        status = 'PASS'
        scope = 'carry-over classification and reproducible Windows/Web release baseline; open blockers remain assigned to G7-1 through G7-6'
        sourcePins = [ordered]@{
            dorotiCommit = $dorotiRevision
            worktreeDirty = @(& git -C $repoRoot status --porcelain).Count -gt 0
            flutter = '56b8e1a851a594b1a154f8ea93270807dab22b9a'
        }
        representativeFixtures = @(
            [ordered]@{ id='windows-product-smoke'; evidence='g7-windows-product-smoke.json'; selectionReason=$product.fixture.selectionReason; capabilities=$product.fixture.capabilities },
            [ordered]@{ id='managed-focus-frame-dispatch'; evidence='g7-managed-regression.json'; selectionReason='first current failure in the predecessor managed Widgets regression'; capabilities=@('focus-request','microtask','view-frame-dispatch') },
            [ordered]@{ id='calendar-date-picker'; evidence='g6-material-visual-differential.json'; selectionReason='existing fidelity-risk fixture spanning glyph, baseline, grid, state, corner, and shadow'; capabilities=@('material-reference') }
        )
        verifiedPredecessor = @(
            [ordered]@{ id='widgets-live'; status=$widgets.status; evidence='g6-widgets-live-evidence.json'; boundary='Windows automated strict-GPU' },
            [ordered]@{ id='material-demo'; status=$materialDemo.status; evidence='g6-material-demo-evidence.json'; boundary='Windows automated strict-GPU' },
            [ordered]@{ id='app-slices'; status=$appSlices.status; evidence='g6-app-slices.json'; boundary='Windows automated strict-GPU' },
            [ordered]@{ id='material-presented'; status='verified-predecessor'; evidence='g6-material-component-matrix.json'; detail='54/60 presented; native input remains separate' },
            [ordered]@{ id='pointer-calendar'; status=$pointer.status; evidence='g6-pointer-interaction-evidence.json'; boundary='one Windows native causal fixture' },
            [ordered]@{ id='compositing-c0'; status=$compositing.status; evidence='g6-compositing-effects-evidence.json'; boundary='C0 managed and Windows strict-GPU only' },
            [ordered]@{ id='cupertino-presented'; status='verified-predecessor'; evidence='g6-cupertino-component-matrix.json'; detail='55/55 presented; interaction remains partial' },
            [ordered]@{ id='generated-windows-package'; status='verified-predecessor-partial'; evidence='g6-generated-demo-evidence.json'; boundary='Windows package/compiler/live slices; parity prerequisites open' }
        )
        releaseBlockers = $blockers
        stale = @(
            [ordered]@{ id='g6-appbar-live-smoke'; evidence='g6-live-smoke.json'; reason='G6-0 AppBar failure was superseded by G6-3 verified Material product presentation'; allowedAsActivePass=$false },
            [ordered]@{ id='g6-appbar-runtime-taxonomy'; evidence='g6-runtime-error-taxonomy.json'; reason='historical G6-0 blocker; its reproduction command is no longer an active G7 gate'; allowedAsActivePass=$false },
            [ordered]@{ id='g6-initial-component-lifecycle-counts'; evidence='g6-component-coverage.json'; reason='initial notVerified lifecycle census was superseded by later live matrices'; allowedAsActivePass=$false }
        )
        deferred = @('linux-desktop','macos-desktop','firefox','webkit','touch','multi-monitor','long-duration-gpu-soak')
        consistency = [ordered]@{
            activeReleaseBlockers = $blockers.Count
            blockersMissingOwnerCommandOrMilestone = $missingMetadata
            stalePassesInActiveReleaseGate = $invalidPasses
            historicalCountsReaggregated = $false
        }
        validationShards = @(
            [ordered]@{ name='Compatibility'; command='validate-g7-baseline.ps1 -Shard Compatibility'; maxMinutes=20; status='PASS-open-debt-recorded' },
            [ordered]@{ name='ManagedRegression'; command='validate-g7-baseline.ps1 -Shard ManagedRegression'; maxMinutes=20; status='PASS-blocker-reproduced' },
            [ordered]@{ name='Product'; command='validate-g7-baseline.ps1 -Shard Product'; maxMinutes=20; status='PASS' },
            [ordered]@{ name='FormatBaseline'; command='validate-g7-baseline.ps1 -Shard FormatBaseline'; maxMinutes=20; status='PASS-blocker-reproduced' },
            [ordered]@{ name='Evidence'; command='validate-g7-baseline.ps1 -Shard Evidence'; maxMinutes=20; status='PASS' },
            [ordered]@{ name='Build'; command='validate-g7-baseline.ps1 -Shard Build'; maxMinutes=20; status='PASS' }
        )
        artifacts = [ordered]@{
            compatibilityDebt='migration/flutter-framework/g7-compatibility-debt.json'
            managedRegression='migration/flutter-framework/g7-managed-regression.json'
            windowsProductSmoke='migration/flutter-framework/g7-windows-product-smoke.json'
            formatBaseline='migration/flutter-framework/g7-format-baseline.json'
            targetMatrix='migration/targets/g7-target-matrix.json'
        }
    })
    Write-Output "G7-0 carry-over evidence: PASS ($($blockers.Count) assigned release blockers, 0 stale PASS claims, required targets separated from deferred targets)"
}

function Invoke-BuildShard {
    Invoke-Checked {
        dotnet build (Join-Path $dorotiRoot 'Doroti.slnx') --configuration Release --nologo --disable-build-servers --tl:off -nodeReuse:false
    } 'G7-0 Doroti Release build failed'
    Invoke-Checked { git -C $repoRoot diff --check } 'G7-0 git diff check failed'
    Write-Output 'G7-0 Release build and diff check: PASS'
}

if (Test-Shard 'Compatibility') { Invoke-CompatibilityShard }
if (Test-Shard 'ManagedRegression') { Invoke-ManagedRegressionShard }
if (Test-Shard 'Product') { Invoke-ProductShard }
if (Test-Shard 'FormatBaseline') { Invoke-FormatBaselineShard }
if (Test-Shard 'Evidence') { Invoke-EvidenceShard }
if (Test-Shard 'Build') { Invoke-BuildShard }

Write-Output "G7-0 baseline validation shard '$Shard': PASS"
