name: doroti_demo_app
description: Goal7 generated Dart DemoApp package for Doroti.
version: 0.2.0
environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/brand.txt
  fonts:
    - family: Doroti Sans
      fonts:
        - asset: assets/DorotiSans.font
