<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Doroti.Validation.G7Shared</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Doroti.Flutter.Hosting\Doroti.Flutter.Hosting.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Target.Windows.win-x64\Doroti.Target.Windows.win-x64.csproj" />
  </ItemGroup>
</Project>
