namespace Doroti.Host.WindowsAppSdk;

internal sealed record AcrylicPresenterSnapshot(
    string RequestedMode,
    string EffectiveMode,
    string? FallbackReason,
    bool PresentationSupported,
    bool IndependentFlipSupported,
    string AdapterLuid,
    uint AdapterVendorId,
    uint AdapterDeviceId,
    string AcrylicKind,
    string Theme,
    uint? TintColor,
    double? TintOpacity,
    double? LuminosityOpacity,
    int LogicalActiveEdgeBudget,
    int PhysicalActiveEdgeBudget,
    ulong MaximumRegisteredSlots,
    ulong AvailableReuseCount,
    ulong UnavailableSkipCount,
    long AcceptedOptionRevisions,
    long AppliedOptionRevisions,
    long SupersededOptionRevisions,
    long FailedOptionRevisions,
    bool BackdropTargetAdded,
    bool ContentIslandConnected,
    bool DesktopWindowTargetConnected = false,
    bool HostBackdropBrushEnabled = false,
    string BackdropTransport = "DesktopAcrylicController",
    string? SystemBackdropType = null,
    bool RedirectionBitmapAlphaEnabled = false,
    string? BackdropState = null
);
