<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Doroti.Validation.RuntimeShaderContract</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Doroti.Skia.RuntimeEffects\Doroti.Skia.RuntimeEffects.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Ui\Doroti.Ui.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Framework.Widgets\Doroti.Framework.Widgets.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Framework.Material\Doroti.Framework.Material.csproj" />
  </ItemGroup>
</Project>
