<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Doroti.Shell.Core</AssemblyName>
    <IsDorotiProduct>true</IsDorotiProduct>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Doroti.Graphics\Doroti.Graphics.csproj" />
    <ProjectReference Include="..\Doroti.Platform\Doroti.Platform.csproj" />
  </ItemGroup>
</Project>
