<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Doroti.Graphics\Doroti.Graphics.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Host.Avalonia\Doroti.Host.Avalonia.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Host.Desktop\Doroti.Host.Desktop.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Platform\Doroti.Platform.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Vendor.Avalonia.Win32\Doroti.Vendor.Avalonia.Win32.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
  </ItemGroup>
</Project>
