<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault></PropertyGroup><ItemGroup><ProjectReference Include="../../src/Doroti.Tooling.Extension.Sdk/Doroti.Tooling.Extension.Sdk.csproj"/><ProjectReference Include="../fixtures/test-headless/tooling/TestHeadless.Tool.csproj"/></ItemGroup></Project>
