<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Doroti.Composition</AssemblyName>
    <IsDorotiProduct>true</IsDorotiProduct>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Doroti.Core\Doroti.Core.csproj" />
    <ProjectReference Include="..\Doroti.Graphics\Doroti.Graphics.csproj" />
  </ItemGroup>
</Project>
