<Project>
  <ItemGroup Condition="'$(DorotiTarget)' == 'Windows'">
    <DorotiNativePlugin Include="doroti.native-features" HandlerType="Doroti.Plugins.NativeFeaturesHandler"
      Channel="doroti/native-features" Codec="json" AbiVersion="1" PackageId="Doroti.Plugins" Version="0.3.0-beta" Rid="$(RuntimeIdentifier)" />
  </ItemGroup>
</Project>
