<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Doroti.Framework.Physics\Doroti.Framework.Physics.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Framework.Animation\Doroti.Framework.Animation.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Framework.Gestures\Doroti.Framework.Gestures.csproj" />
  </ItemGroup>
</Project>
