<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SkiaSharp" />
    <ProjectReference Include="..\..\src\Doroti.Backends.Skia\Doroti.Backends.Skia.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Framework.Painting\Doroti.Framework.Painting.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Framework.Rendering\Doroti.Framework.Rendering.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Framework.Semantics\Doroti.Framework.Semantics.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Ui\Doroti.Ui.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Host.Desktop\Doroti.Host.Desktop.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Host.Desktop.Framework\Doroti.Host.Desktop.Framework.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Vendor.Avalonia.Win32\Doroti.Vendor.Avalonia.Win32.csproj" />
  </ItemGroup>
</Project>
