<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><OutputType>Exe</OutputType><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><EnableDynamicLoading>true</EnableDynamicLoading><IsPackable>true</IsPackable><PackageId>Doroti.TestProvider.Tool</PackageId><Version>0.4.0-alpha.1</Version><JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault></PropertyGroup><ItemGroup><ProjectReference Include="../../../../src/Doroti.Tooling.Extension.Sdk/Doroti.Tooling.Extension.Sdk.csproj"/><None Include="doroti-provider.json" Pack="true" PackagePath="lib/net10.0/"/></ItemGroup></Project>
