<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Doroti.Runner.Sdk" Version="0.2.0-beta" />
  <PropertyGroup>
    <TargetFramework>net10.0-maccatalyst</TargetFramework>
    <RuntimeIdentifier>maccatalyst-arm64</RuntimeIdentifier>
    <AssemblyName>DorotiTemplateApp.MacCatalyst</AssemblyName>
    <RootNamespace>DorotiTemplateApp.MacCatalyst</RootNamespace>
    <DorotiAppProject>..\DorotiTemplateApp.csproj</DorotiAppProject>
    <DorotiTarget>MacCatalyst</DorotiTarget>
    <DorotiHostKind>Maui</DorotiHostKind>
    <DorotiNativeEntryKind>UIKit-Main</DorotiNativeEntryKind>
    <UseMaui>true</UseMaui>
    <DefineConstants>$(DefineConstants);MACCATALYST;DOROTI_MAUI</DefineConstants>
    <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
  </PropertyGroup>
  <ItemGroup>
    <DorotiNativeBindingProject Include="binding\DorotiTemplateApp.MacCatalyst.Native.csproj" />
    <DorotiTargetDescriptor Include="MacCatalyst" HostKind="Maui" NativeEntryKind="UIKit-Main" RuntimeIdentifier="maccatalyst-arm64" TargetFramework="net10.0-maccatalyst" TargetPackage="Doroti.Target.MacCatalyst.Maui.maccatalyst-arm64" />
    <PackageReference Include="Doroti.Target.MacCatalyst.Maui.maccatalyst-arm64" Version="0.2.0-beta" />
  </ItemGroup>
</Project>
