<Project>
  <Import Project="../../Directory.Build.props" />
  <PropertyGroup>
    <ApplicationTitle>Doroti Material Testbed</ApplicationTitle>
    <ApplicationId>dev.doroti.testbed</ApplicationId>
    <ApplicationDisplayVersion>0.4.0</ApplicationDisplayVersion>
    <ApplicationVersion>4</ApplicationVersion>
  </PropertyGroup>
</Project>
