<Project>
  <PropertyGroup>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">linux-x64</RuntimeIdentifier>
    <BaseIntermediateOutputPath>obj\$(RuntimeIdentifier)\</BaseIntermediateOutputPath>
    <BaseOutputPath>bin\$(RuntimeIdentifier)\</BaseOutputPath>
    <NuGetLockFilePath>packages.$(RuntimeIdentifier).lock.json</NuGetLockFilePath>
  </PropertyGroup>
</Project>
