<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>Doroti.Validation.LinuxQtContract</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Doroti.Host.Qt\Doroti.Host.Qt.csproj" />
  </ItemGroup>
</Project>
