<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Doroti.Host.Desktop</AssemblyName>
    <IsDorotiProduct>true</IsDorotiProduct>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Doroti.Backends.Skia\Doroti.Backends.Skia.csproj" />
    <ProjectReference Include="..\Doroti.Composition\Doroti.Composition.csproj" />
    <ProjectReference Include="..\Doroti.Graphics\Doroti.Graphics.csproj" />
    <ProjectReference Include="..\Doroti.Core\Doroti.Core.csproj" />
    <ProjectReference Include="..\Doroti.Engine\Doroti.Engine.csproj" />
    <ProjectReference Include="..\Doroti.Platform\Doroti.Platform.csproj" />
    <ProjectReference Include="..\Doroti.Rendering\Doroti.Rendering.csproj" />
    <ProjectReference Include="..\Doroti.Shell.Core\Doroti.Shell.Core.csproj" />
    <ProjectReference Include="..\Doroti.Vendor.Avalonia.Base\Doroti.Vendor.Avalonia.Base.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Win32AutomationProvider.cs" />
  </ItemGroup>
</Project>
