<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Doroti.Framework.Rendering</AssemblyName>
    <PackageId>Doroti.Framework.Rendering</PackageId>
    <IsDorotiProduct>true</IsDorotiProduct>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Doroti.Framework.Widgets.Widgets" />
    <InternalsVisibleTo Include="Doroti.Framework.Widgets" />
    <ProjectReference Include="..\Doroti.Runtime\Doroti.Runtime.csproj" />
    <ProjectReference Include="..\Doroti.Ui\Doroti.Ui.csproj" />
    <ProjectReference Include="..\Doroti.Framework.Foundation\Doroti.Framework.Foundation.csproj" />
    <ProjectReference Include="..\Doroti.Framework.Scheduler\Doroti.Framework.Scheduler.csproj" />
    <ProjectReference Include="..\Doroti.Framework.Services\Doroti.Framework.Services.csproj" />
    <ProjectReference Include="..\Doroti.Framework.Physics\Doroti.Framework.Physics.csproj" />
    <ProjectReference Include="..\Doroti.Framework.Animation\Doroti.Framework.Animation.csproj" />
    <ProjectReference Include="..\Doroti.Framework.Gestures\Doroti.Framework.Gestures.csproj" />
    <ProjectReference Include="..\Doroti.Framework.Painting\Doroti.Framework.Painting.csproj" />
    <ProjectReference Include="..\Doroti.Framework.Semantics\Doroti.Framework.Semantics.csproj" />
  </ItemGroup>
</Project>
