<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Doroti.Backends.Skia</AssemblyName>
    <IsDorotiProduct>true</IsDorotiProduct>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Doroti.Validation.G6MaterialFidelity" />
    <PackageReference Include="SkiaSharp" />
    <ProjectReference Include="..\Doroti.Core\Doroti.Core.csproj" />
    <ProjectReference Include="..\Doroti.Platform\Doroti.Platform.csproj" />
    <ProjectReference Include="..\Doroti.Graphics\Doroti.Graphics.csproj" />
    <ProjectReference Include="..\Doroti.Composition\Doroti.Composition.csproj" />
    <ProjectReference Include="..\Doroti.Vendor.Avalonia.Skia\Doroti.Vendor.Avalonia.Skia.csproj" />
  </ItemGroup>
</Project>
