<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Doroti.Validation.G6Cupertino</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Doroti.Backends.Skia\Doroti.Backends.Skia.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Hosting\Doroti.Hosting.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Framework.Cupertino\Doroti.Framework.Cupertino.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Framework.WidgetPreviews\Doroti.Framework.WidgetPreviews.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Target.Windows.win-x64\Doroti.Target.Windows.win-x64.csproj" />
  </ItemGroup>
</Project>
