using System.Globalization;

namespace Doroti.DartToCSharp;

internal sealed record PrintedOrigin(CsOrigin Origin, int StartLine, int EndLine);
internal sealed record PrintedCompilation(string Text, PrintedOrigin[] Origins);

internal sealed class CSharpPrinter
{
    private readonly CSharpWriter _writer = new();
    private readonly List<PrintedOrigin> _origins = [];
    private int _indent;

    public PrintedCompilation Print(CsCompilationUnit unit)
    {
        _writer.AppendLine("// <auto-generated />");
        _writer.AppendLine("#nullable enable");
        foreach (var item in unit.Usings
                     .OrderBy(item => item.Alias, StringComparer.Ordinal)
                     .ThenBy(item => item.Namespace, StringComparer.Ordinal))
        {
            _writer.Append("using ");
            if (item.IsStatic)
            {
                _writer.Append("static ");
            }
            if (item.Alias is not null)
            {
                _writer.Append(item.Alias).Append(" = ");
            }
            _writer.Append(item.Namespace).AppendLine(";");
        }
        _writer.AppendLine().Append("namespace ").Append(unit.Namespace).AppendLine(";").AppendLine();

        foreach (var declaration in unit.Declarations)
        {
            PrintDeclaration(declaration);
        }
        return new(_writer.ToString(), _origins.ToArray());
    }

    public PrintedCompilation Print(CsSyntaxDocument document)
    {
        var orderedRegions = document.Regions
            .OrderBy(item => item.StartOffset)
            .ThenByDescending(item => item.EndOffset)
            .ToArray();
        var startLines = new Dictionary<CsSyntaxRegion, int>();
        var endLines = new Dictionary<CsSyntaxRegion, int>();
        var regionsByStart = orderedRegions
            .GroupBy(item => item.StartOffset)
            .ToDictionary(group => group.Key, group => group.ToArray());
        var regionsByEnd = orderedRegions
            .GroupBy(item => item.EndOffset)
            .ToDictionary(group => group.Key, group => group.ToArray());

        foreach (var token in document.Tokens)
        {
            if (regionsByStart.TryGetValue(token.StartOffset, out var startingRegions))
            {
                foreach (var region in startingRegions)
                {
                    startLines[region] = _writer.CurrentLine;
                }
            }
            _writer.Append(token.Text);
            if (regionsByEnd.TryGetValue(token.EndOffset, out var endingRegions))
            {
                foreach (var region in endingRegions)
                {
                    endLines[region] = _writer.LineCount;
                }
            }
        }

        foreach (var region in orderedRegions)
        {
            startLines.TryAdd(region, 1);
            endLines.TryAdd(region, _writer.LineCount);
        }

        return new(
            _writer.ToString(),
            orderedRegions
                .Where(item => item.Kind == CsSyntaxRegionKind.Declaration)
                .Select(item => new PrintedOrigin(item.Origin, startLines[item], endLines[item]))
                .ToArray());
    }

    private void PrintDeclaration(CsDeclaration declaration)
    {
        var start = _writer.CurrentLine;
        switch (declaration)
        {
            case CsTypeDeclaration type:
                PrintType(type);
                break;
            case CsDelegateDeclaration item:
                WriteIndent();
                PrintAccessibility(item.Accessibility);
                _writer.Append("delegate ");
                PrintTypeReference(item.ReturnType);
                _writer.Append(' ').Append(item.Name);
                PrintTypeParameters(item.TypeParameters);
                PrintParameters(item.Parameters);
                _writer.AppendLine(";").AppendLine();
                break;
        }
        _origins.Add(new(declaration.Origin, start, _writer.LineCount));
    }

    private void PrintType(CsTypeDeclaration type)
    {
        WriteIndent();
        PrintAccessibility(type.Accessibility);
        if (type.IsStatic) _writer.Append("static ");
        if (type.IsAbstract) _writer.Append("abstract ");
        if (type.IsSealed) _writer.Append("sealed ");
        if (type.IsPartial) _writer.Append("partial ");
        _writer.Append(type.Kind.ToString().ToLowerInvariant()).Append(' ').Append(type.Name);
        PrintTypeParameters(type.TypeParameters);
        if (type.BaseTypes.Length > 0)
        {
            _writer.Append(" : ");
            PrintSeparated(type.BaseTypes, PrintTypeReference);
        }
        _writer.AppendLine();
        WriteIndent();
        _writer.AppendLine("{");
        _indent++;
        foreach (var member in type.Members)
        {
            PrintMember(member);
        }
        _indent--;
        WriteIndent();
        _writer.AppendLine("}").AppendLine();
    }

    private void PrintMember(CsMember member)
    {
        switch (member)
        {
            case CsField field:
                WriteIndent();
                PrintAccessibility(field.Accessibility);
                if (field.IsConst) _writer.Append("const ");
                else
                {
                    if (field.IsStatic) _writer.Append("static ");
                    if (field.IsReadOnly) _writer.Append("readonly ");
                }
                PrintTypeReference(field.Type);
                _writer.Append(' ').Append(field.Name);
                if (field.Initializer is not null)
                {
                    _writer.Append(" = ");
                    PrintExpression(field.Initializer);
                }
                _writer.AppendLine(";");
                break;
            case CsMethod method:
                WriteIndent();
                PrintAccessibility(method.Accessibility);
                if (method.IsStatic) _writer.Append("static ");
                if (method.IsAbstract) _writer.Append("abstract ");
                if (method.IsOverride) _writer.Append("override ");
                if (method.IsAsync) _writer.Append("async ");
                PrintTypeReference(method.ReturnType);
                _writer.Append(' ').Append(method.Name);
                PrintTypeParameters(method.TypeParameters);
                PrintParameters(method.Parameters);
                if (method.IsAbstract)
                {
                    _writer.AppendLine(";");
                    return;
                }
                _writer.AppendLine().AppendLine("{");
                _indent++;
                foreach (var statement in method.Body) PrintStatement(statement);
                _indent--;
                WriteIndent();
                _writer.AppendLine("}");
                break;
        }
    }

    private void PrintStatement(CsStatement statement)
    {
        WriteIndent();
        switch (statement)
        {
            case CsReturn item:
                _writer.Append("return");
                if (item.Expression is not null)
                {
                    _writer.Append(' ');
                    PrintExpression(item.Expression);
                }
                _writer.AppendLine(";");
                break;
            case CsExpressionStatement item:
                PrintExpression(item.Expression);
                _writer.AppendLine(";");
                break;
            case CsBlock block:
                _writer.AppendLine("{");
                _indent++;
                foreach (var item in block.Statements) PrintStatement(item);
                _indent--;
                WriteIndent();
                _writer.AppendLine("}");
                break;
        }
    }

    private void PrintExpression(CsExpression expression)
    {
        switch (expression)
        {
            case CsLiteral { Value: null }:
                _writer.Append("null");
                break;
            case CsLiteral { Value: string value }:
                _writer.Append('"').Append(Escape(value)).Append('"');
                break;
            case CsLiteral { Value: bool value }:
                _writer.Append(value ? "true" : "false");
                break;
            case CsLiteral item:
                _writer.Append(Convert.ToString(item.Value, CultureInfo.InvariantCulture));
                break;
            case CsIdentifier item:
                _writer.Append(item.Name);
                break;
            case CsMemberAccess item:
                PrintExpression(item.Target);
                _writer.Append('.').Append(item.Name);
                break;
            case CsInvocation item:
                PrintExpression(item.Target);
                _writer.Append('(');
                PrintSeparated(item.Arguments, PrintExpression);
                _writer.Append(')');
                break;
        }
    }

    private void PrintParameters(CsParameter[] parameters)
    {
        _writer.Append('(');
        PrintSeparated(parameters, parameter =>
        {
            PrintTypeReference(parameter.Type);
            _writer.Append(' ').Append(parameter.Name);
            if (parameter.DefaultValue is not null)
            {
                _writer.Append(" = ");
                PrintExpression(parameter.DefaultValue);
            }
        });
        _writer.Append(')');
    }

    private void PrintTypeReference(CsTypeReference type)
    {
        if (type.Namespace.Length > 0) _writer.Append(type.Namespace).Append('.');
        _writer.Append(type.Name);
        if (type.TypeArguments.Length > 0)
        {
            _writer.Append('<');
            PrintSeparated(type.TypeArguments, PrintTypeReference);
            _writer.Append('>');
        }
        if (type.IsNullable) _writer.Append('?');
    }

    private void PrintTypeParameters(string[] parameters)
    {
        if (parameters.Length == 0) return;
        _writer.Append('<').Append(string.Join(", ", parameters)).Append('>');
    }

    private void PrintAccessibility(CsAccessibility accessibility) =>
        _writer.Append(accessibility.ToString().ToLowerInvariant()).Append(' ');

    private void PrintSeparated<T>(IReadOnlyList<T> values, Action<T> print)
    {
        for (var index = 0; index < values.Count; index++)
        {
            if (index > 0) _writer.Append(", ");
            print(values[index]);
        }
    }

    private void WriteIndent() => _writer.Append(new string(' ', _indent * 4));

    private static string Escape(string value) => value
        .Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal)
        .Replace("\r", "\\r", StringComparison.Ordinal)
        .Replace("\n", "\\n", StringComparison.Ordinal);
}
