<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Doroti.Validation.MauiKeyboard</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Doroti.Hosting/Doroti.Hosting.csproj" />
    <Compile Include="../../src/Doroti.Host.Maui/MauiKeyMap.cs" Link="MauiKeyMap.cs" />
    <Compile Include="../../src/Doroti.Host.Maui/MauiKeyboardState.cs" Link="MauiKeyboardState.cs" />
  </ItemGroup>
</Project>
