<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Doroti.Validation.ResizeContract</AssemblyName>
    <IsDorotiProduct>false</IsDorotiProduct>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Doroti.Ui\Doroti.Ui.csproj" />
  </ItemGroup>
</Project>
