<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Doroti.Validation.Compiler</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\tools\Doroti.DartToCSharp\Doroti.DartToCSharp.csproj" />
    <ProjectReference Include="..\..\tools\Doroti.SourceTools\Doroti.SourceTools.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Framework.Foundation\Doroti.Framework.Foundation.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Framework.Physics\Doroti.Framework.Physics.csproj" />
  </ItemGroup>
</Project>
