<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Doroti.Hosting</AssemblyName>
    <PackageId>Doroti.Hosting</PackageId>
    <IsDorotiProduct>true</IsDorotiProduct>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Doroti.Host.Maui" />
    <InternalsVisibleTo Include="Doroti.Host.WindowsAppSdk" />
    <InternalsVisibleTo Include="Doroti.Validation.MauiKeyboard" />
    <ProjectReference Include="..\Doroti.Runtime\Doroti.Runtime.csproj" />
    <ProjectReference Include="..\Doroti.Ui\Doroti.Ui.csproj" />
  </ItemGroup>
</Project>
