<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Doroti.Widgets</AssemblyName>
    <IsDorotiProduct>false</IsDorotiProduct>
    <IsPackable>false</IsPackable>
    <DorotiLegacyCompatibility>true</DorotiLegacyCompatibility>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Doroti.Flutter.Framework.Foundation\Doroti.Flutter.Framework.Foundation.csproj" />
    <ProjectReference Include="..\Doroti.Flutter.Framework.Animation\Doroti.Flutter.Framework.Animation.csproj" />
    <ProjectReference Include="..\Doroti.Flutter.Framework.Gestures\Doroti.Flutter.Framework.Gestures.csproj" />
    <ProjectReference Include="..\Doroti.Core\Doroti.Core.csproj" />
    <ProjectReference Include="..\Doroti.Platform\Doroti.Platform.csproj" />
    <ProjectReference Include="..\Doroti.Rendering\Doroti.Rendering.csproj" />
    <ProjectReference Include="..\Doroti.Legacy.Rendering\Doroti.Legacy.Rendering.csproj" />
  </ItemGroup>
</Project>
