namespace Doroti.Widgets;

// <auto-generated>
// flutter-f3-generated
// Typed source-port inputs: widgets/framework.dart and rendering/object.dart at Flutter
// 56b8e1a851a594b1a154f8ea93270807dab22b9a. This file owns the generated
// ordering/matching portion; lifecycle mutation and native resource bindings remain adapted.
// </auto-generated>

internal static class FlutterF3DirtyElementOrder
{
    internal static Element Next(IReadOnlyCollection<Element> dirty) => dirty
        .OrderBy(element => element.Depth)
        .ThenBy(element => element.DirtySequence)
        .First();
}

internal static class FlutterF3ElementDiff
{
    internal static Element? Match(
        IReadOnlyList<Element> oldChildren,
        IReadOnlySet<Element> used,
        Widget newWidget,
        int newIndex)
    {
        if (newIndex < oldChildren.Count &&
            !used.Contains(oldChildren[newIndex]) &&
            Widget.CanUpdate(oldChildren[newIndex].Widget, newWidget))
        {
            return oldChildren[newIndex];
        }

        if (newWidget.Key is not null)
        {
            return oldChildren.FirstOrDefault(element =>
                !used.Contains(element) &&
                Equals(element.Widget.Key, newWidget.Key) &&
                Widget.CanUpdate(element.Widget, newWidget));
        }

        return oldChildren.FirstOrDefault(element =>
            !used.Contains(element) && element.Widget.Key is null && Widget.CanUpdate(element.Widget, newWidget));
    }
}
