using Doroti.Graphics;
using FlutterAnimation = Doroti.Generated.Framework.Animation;

namespace Doroti.Widgets;

// <auto-generated>
// flutter-f2-generated
// Source-port inputs: physics/{simulation,tolerance,friction_simulation}.dart,
// widgets/scroll_simulation.dart, animation/curves.dart,
// gestures/{resampler,velocity_tracker}.dart at Flutter
// 56b8e1a851a594b1a154f8ea93270807dab22b9a.
// The generator/audit owns this file; engine and platform bindings remain outside it.
// </auto-generated>

public readonly record struct SimulationTolerance(double Distance = 0.001, double Time = 0.001, double Velocity = 0.001)
{
    public static SimulationTolerance Default { get; } = new();
}

public abstract class Simulation
{
    protected Simulation(SimulationTolerance? tolerance = null) => Tolerance = tolerance ?? SimulationTolerance.Default;

    public SimulationTolerance Tolerance { get; }

    public abstract double X(double timeSeconds);

    public abstract double Dx(double timeSeconds);

    public abstract bool IsDone(double timeSeconds);
}

public class FrictionSimulation : Simulation
{
    private readonly double _drag;
    private readonly double _dragLog;
    private readonly double _position;
    private readonly double _velocity;
    private readonly double _constantDeceleration;
    private readonly double _finalTime;

    public FrictionSimulation(
        double drag,
        double position,
        double velocity,
        SimulationTolerance? tolerance = null,
        double constantDeceleration = 0)
        : base(tolerance)
    {
        if (!double.IsFinite(drag) || drag <= 0 || drag == 1 || !double.IsFinite(position) ||
            !double.IsFinite(velocity) || !double.IsFinite(constantDeceleration) || constantDeceleration < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(drag));
        }
        _drag = drag;
        _dragLog = Math.Log(drag);
        _position = position;
        _velocity = velocity;
        _constantDeceleration = constantDeceleration * Math.Sign(velocity);
        _finalTime = constantDeceleration == 0
            ? double.PositiveInfinity
            : Newton(0, 0, UnboundedDx, time => (_velocity * Math.Pow(_drag, time) * _dragLog) - _constantDeceleration);
    }

    public double FinalX => _constantDeceleration == 0 ? _position - (_velocity / _dragLog) : UnboundedX(_finalTime);

    public override double X(double timeSeconds) => timeSeconds > _finalTime ? FinalX : UnboundedX(timeSeconds);

    public override double Dx(double timeSeconds) => timeSeconds > _finalTime ? 0 : UnboundedDx(timeSeconds);

    public override bool IsDone(double timeSeconds) => Math.Abs(Dx(timeSeconds)) < Tolerance.Velocity;

    public double TimeAtX(double position)
    {
        if (position == _position)
        {
            return 0;
        }
        if (_velocity == 0 || (_velocity > 0
            ? position < _position || position > FinalX
            : position > _position || position < FinalX))
        {
            return double.PositiveInfinity;
        }
        return Newton(0, position, X, Dx);
    }

    private double UnboundedX(double time) => _position +
        (_velocity * Math.Pow(_drag, time) / _dragLog) -
        (_velocity / _dragLog) -
        ((_constantDeceleration / 2) * time * time);

    private double UnboundedDx(double time) => (_velocity * Math.Pow(_drag, time)) - (_constantDeceleration * time);

    private static double Newton(double guess, double target, Func<double, double> function, Func<double, double> derivative)
    {
        for (var iteration = 0; iteration < 10; iteration++)
        {
            guess -= (function(guess) - target) / derivative(guess);
        }
        return guess;
    }
}

public sealed class BoundedFrictionSimulation : FrictionSimulation
{
    private readonly double _minimum;
    private readonly double _maximum;

    public BoundedFrictionSimulation(double drag, double position, double velocity, double minimum, double maximum, SimulationTolerance? tolerance = null)
        : base(drag, position, velocity, tolerance)
    {
        if (minimum > maximum || position < minimum || position > maximum)
        {
            throw new ArgumentOutOfRangeException(nameof(position));
        }
        _minimum = minimum;
        _maximum = maximum;
    }

    public override double X(double timeSeconds) => Math.Clamp(base.X(timeSeconds), _minimum, _maximum);

    public override bool IsDone(double timeSeconds) => base.IsDone(timeSeconds) ||
        Math.Abs(X(timeSeconds) - _minimum) < Tolerance.Distance ||
        Math.Abs(X(timeSeconds) - _maximum) < Tolerance.Distance;
}

/// <summary>Flutter's Android-compatible spline fling model from widgets/scroll_simulation.dart.</summary>
public sealed class FlutterClampingScrollSimulation : Simulation
{
    private static readonly double DecelerationRate = Math.Log(0.78) / Math.Log(0.9);
    private const double Inflexion = 0.35;
    private const double PhysicalCoefficient = 9.80665 * 39.37 * 160 * 0.84;
    private readonly double _position;
    private readonly double _velocity;
    private readonly double _duration;
    private readonly double _distance;

    public FlutterClampingScrollSimulation(double position, double velocity, double friction = 0.015, SimulationTolerance? tolerance = null)
        : base(tolerance)
    {
        if (!double.IsFinite(position) || !double.IsFinite(velocity) || !double.IsFinite(friction) || friction <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(position));
        }
        _position = position;
        _velocity = velocity;
        var referenceVelocity = friction * PhysicalCoefficient / Inflexion;
        var androidDuration = Math.Pow(Math.Abs(velocity) / referenceVelocity, 1 / (DecelerationRate - 1));
        _duration = DecelerationRate * Inflexion * androidDuration;
        _distance = velocity * _duration / DecelerationRate;
    }

    public double DurationSeconds => _duration;

    public double FinalX => _position + _distance;

    public override double X(double timeSeconds)
    {
        var t = _duration == 0 ? 1 : Math.Clamp(timeSeconds / _duration, 0, 1);
        return _position + (_distance * (1 - Math.Pow(1 - t, DecelerationRate)));
    }

    public override double Dx(double timeSeconds)
    {
        var t = _duration == 0 ? 1 : Math.Clamp(timeSeconds / _duration, 0, 1);
        return _velocity * Math.Pow(1 - t, DecelerationRate - 1);
    }

    public override bool IsDone(double timeSeconds) => timeSeconds >= _duration;
}

public sealed class CubicCurve(double a, double b, double c, double d)
{
    private readonly FlutterAnimation.Cubic _inner = new(a, b, c, d);

    public double Transform(double value) => _inner.transform(value);
}

public static class FlutterCurves
{
    public static FlutterAnimation.Curve Linear => FlutterAnimation.Curves.linear;

    public static FlutterAnimation.Curve Ease => FlutterAnimation.Curves.ease;

    public static FlutterAnimation.Curve FastOutSlowIn => FlutterAnimation.Curves.fastOutSlowIn;
}

public readonly record struct VelocityEstimate(Offset PixelsPerSecond, double Confidence, TimeSpan Duration, Offset Offset);

public sealed class PointerVelocityTracker
{
    private readonly Queue<(TimeSpan Time, Offset Position)> _samples = [];

    public void AddPosition(TimeSpan timestamp, Offset position)
    {
        _samples.Enqueue((timestamp, position));
        while (_samples.Count > 20 || _samples.Count > 1 && timestamp - _samples.Peek().Time > TimeSpan.FromMilliseconds(100))
        {
            _samples.Dequeue();
        }
    }

    public VelocityEstimate? GetVelocityEstimate()
    {
        if (_samples.Count < 2)
        {
            return null;
        }
        var values = _samples.ToArray();
        var first = values[0];
        var last = values[^1];
        var duration = last.Time - first.Time;
        if (duration <= TimeSpan.Zero)
        {
            return null;
        }
        var meanTime = values.Average(sample => (sample.Time - first.Time).TotalSeconds);
        var meanX = values.Average(sample => sample.Position.X);
        var meanY = values.Average(sample => sample.Position.Y);
        var denominator = values.Sum(sample => Math.Pow((sample.Time - first.Time).TotalSeconds - meanTime, 2));
        if (denominator <= double.Epsilon)
        {
            return null;
        }
        var velocity = new Offset(
            values.Sum(sample => ((sample.Time - first.Time).TotalSeconds - meanTime) * (sample.Position.X - meanX)) / denominator,
            values.Sum(sample => ((sample.Time - first.Time).TotalSeconds - meanTime) * (sample.Position.Y - meanY)) / denominator);
        return new(velocity, 1, duration, last.Position - first.Position);
    }
}

public readonly record struct ResampledPointerSample(TimeSpan Timestamp, Offset Position, Offset Delta);

public sealed class PointerEventResampler
{
    private readonly Queue<(TimeSpan Time, Offset Position)> _samples = [];
    private Offset? _lastOutput;

    public void AddSample(TimeSpan timestamp, Offset position) => _samples.Enqueue((timestamp, position));

    public ResampledPointerSample? Sample(TimeSpan timestamp)
    {
        while (_samples.Count >= 2 && _samples.ElementAt(1).Time <= timestamp)
        {
            _samples.Dequeue();
        }
        if (_samples.Count == 0)
        {
            return null;
        }
        var first = _samples.Peek();
        var next = _samples.Count > 1 ? _samples.ElementAt(1) : first;
        var interval = (next.Time - first.Time).TotalSeconds;
        var scalar = interval <= 0 ? 1 : Math.Clamp((timestamp - first.Time).TotalSeconds / interval, 0, 1);
        var position = new Offset(
            first.Position.X + ((next.Position.X - first.Position.X) * scalar),
            first.Position.Y + ((next.Position.Y - first.Position.Y) * scalar));
        var delta = _lastOutput is { } previous ? position - previous : Offset.Zero;
        _lastOutput = position;
        return new(timestamp, position, delta);
    }
}
