<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Doroti.Flutter.Framework.Scheduler</AssemblyName>
    <PackageId>Doroti.Flutter.Framework.Scheduler</PackageId>
    <IsDorotiProduct>true</IsDorotiProduct>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Doroti.Flutter.Runtime\Doroti.Flutter.Runtime.csproj" />
    <ProjectReference Include="..\Doroti.Flutter.Ui\Doroti.Flutter.Ui.csproj" />
    <ProjectReference Include="..\Doroti.Flutter.Framework.Foundation\Doroti.Flutter.Framework.Foundation.csproj" />
  </ItemGroup>
</Project>
