<Project>
  <Import Project="../../Directory.Build.props" />
  <PropertyGroup>
    <ApplicationTitle>Doroti Cupertino Sample</ApplicationTitle>
    <ApplicationId>dev.doroti.sample2</ApplicationId>
    <ApplicationDisplayVersion>0.4.0</ApplicationDisplayVersion>
    <ApplicationVersion>4</ApplicationVersion>
  </PropertyGroup>
</Project>
