<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>DorotiDemoApp</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="WebHost\**\*.cs" />
    <ProjectReference Include="..\Doroti\src\Doroti.Hosting\Doroti.Hosting.csproj" />
    <ProjectReference Include="..\Doroti\src\Doroti.Framework.Widgets\Doroti.Framework.Widgets.csproj" />
    <ProjectReference Include="..\Doroti\src\Doroti.Framework.Material\Doroti.Framework.Material.csproj" />
    <ProjectReference Include="..\Doroti\src\Doroti.Target.Windows.win-x64\Doroti.Target.Windows.win-x64.csproj"
                      Condition="('$(RuntimeIdentifier)' == '' And $([MSBuild]::IsOSPlatform('Windows'))) Or '$(RuntimeIdentifier)' == 'win-x64'" />
    <ProjectReference Include="..\Doroti\src\Doroti.Target.macOS.osx-arm64\Doroti.Target.macOS.osx-arm64.csproj"
                      Condition="('$(RuntimeIdentifier)' == '' And $([MSBuild]::IsOSPlatform('OSX'))) Or '$(RuntimeIdentifier)' == 'osx-arm64'" />
  </ItemGroup>
</Project>
