<Project>
  <Import Project="..\Doroti\src\Doroti.App.Sdk\Sdk\Sdk.props" />
  <PropertyGroup>
    <AssemblyName>DorotiDemoApp</AssemblyName>
    <RootNamespace>DorotiDemoApp</RootNamespace>
    <DorotiUseRepositoryProjects>true</DorotiUseRepositoryProjects>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Doroti\src\Doroti.Hosting\Doroti.Hosting.csproj" />
    <ProjectReference Include="..\Doroti\src\Doroti.Framework.Widgets\Doroti.Framework.Widgets.csproj" />
    <ProjectReference Include="..\Doroti\src\Doroti.Framework.Material\Doroti.Framework.Material.csproj" />
  </ItemGroup>
  <Import Project="..\Doroti\src\Doroti.App.Sdk\Sdk\Sdk.targets" />
</Project>
