<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><AllowUnsafeBlocks>true</AllowUnsafeBlocks></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Doroti.Framework.Widgets/Doroti.Framework.Widgets.csproj" />
    <ProjectReference Include="../../src/Doroti.Host.Web/Doroti.Host.Web.csproj" />
    <Compile Include="../../src/Doroti.Host.Maui/AndroidPointerMapping.cs" Link="AndroidPointerMapping.cs" />
    <Compile Include="../../src/Doroti.Host.Maui/WindowsPointerMapping.cs" Link="WindowsPointerMapping.cs" />
    <Compile Include="../../src/Doroti.Host.Maui/MauiSurfacePointerData.cs" Link="MauiSurfacePointerData.cs" />
    <Compile Include="../../src/Doroti.Host.Maui/MauiTrackpadGesture.cs" Link="MauiTrackpadGesture.cs" />
    <Compile Include="../../src/Doroti.Host.Maui/AndroidTrackpadGesture.cs" Link="AndroidTrackpadGesture.cs" />
  </ItemGroup>
</Project>
