# Reviewed LGPL-capable Qt runtime modules. Changes require a license review of
# the selected Qt version and its third-party dependencies, not just this list.
function(doroti_check_qt_license_policy root_target)
  set(allowed_modules Core Gui Widgets OpenGL OpenGLWidgets Network DBus
    Quick Qml QmlModels QmlWorkerScript QuickControls2 QuickTemplates2
    WebEngineQuick WebEngineCore WebChannel WebChannelQuick Positioning)
  set(allowed_interfaces QmlIntegration Platform)
  set(pending "${root_target}")
  set(visited)
  while(pending)
    list(POP_FRONT pending current)
    if(current IN_LIST visited OR NOT TARGET "${current}")
      continue()
    endif()
    list(APPEND visited "${current}")
    get_target_property(aliased "${current}" ALIASED_TARGET)
    if(aliased)
      list(APPEND pending "${aliased}")
    endif()
    if(current MATCHES "^Qt6::(.+)$")
      set(module "${CMAKE_MATCH_1}")
      if(NOT module IN_LIST allowed_modules AND NOT module IN_LIST allowed_interfaces)
        message(FATAL_ERROR "Doroti license policy: unreviewed Qt module ${current}")
      endif()
      get_target_property(kind "${current}" TYPE)
      if(module IN_LIST allowed_interfaces AND kind STREQUAL "INTERFACE_LIBRARY")
        # Header-only support target, not a statically linked Qt runtime.
      elseif(NOT kind STREQUAL "SHARED_LIBRARY")
        message(FATAL_ERROR "Doroti license policy: ${current} must be a shared library (got ${kind})")
      endif()
    endif()
    foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES LINK_OPTIONS INTERFACE_LINK_OPTIONS)
      get_target_property(links "${current}" "${property}")
      foreach(link IN LISTS links)
        if(TARGET "${link}")
          list(APPEND pending "${link}")
        else()
          # Include both branches of generator expressions conservatively.
          string(REGEX MATCHALL "[A-Za-z0-9_.+-]+(::[A-Za-z0-9_.+-]+)*" candidates "${link}")
          foreach(candidate IN LISTS candidates)
            if(TARGET "${candidate}")
              list(APPEND pending "${candidate}")
            endif()
          endforeach()
          if(link MATCHES "-lQt6|(^|/)libQt6.*\\.(a|so)")
            message(FATAL_ERROR "Doroti license policy: use reviewed Qt6:: targets, not ${link}")
          endif()
        endif()
      endforeach()
    endforeach()
  endwhile()
endfunction()
