<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>Doroti.Validation.WindowsAppSdkContract</AssemblyName>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Doroti.Host.WindowsAppSdk/Doroti.Host.WindowsAppSdk.csproj" />
  </ItemGroup>
</Project>
