<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Doroti.Flutter.Hosting\Doroti.Flutter.Hosting.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Flutter.Framework.Widgets\Doroti.Flutter.Framework.Widgets.csproj" />
    <ProjectReference Include="..\..\src\Doroti.Target.Windows.win-x64\Doroti.Target.Windows.win-x64.csproj" />
  </ItemGroup>
</Project>
