<Project>
  <ItemGroup Condition="'$(DorotiTarget)' == 'Linux' and '@(DorotiTargetDescriptor)' == ''">
    <DorotiTargetDescriptor Include="Linux" HostKind="Qt" NativeEntryKind="Qt-Main" RuntimeIdentifier="linux-x64" TargetFramework="net10.0" TargetPackage="Doroti.Target.Linux.Qt.linux-x64" />
  </ItemGroup>
</Project>
