<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Doroti.Vendor.Avalonia.Win32</AssemblyName>
    <IsDorotiProduct>true</IsDorotiProduct>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Doroti.Shell.Core\Doroti.Shell.Core.csproj" />
    <ProjectReference Include="..\Doroti.Platform\Doroti.Platform.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Doroti.Host.Desktop" />
    <Compile Include="..\Doroti.Host.Desktop\Win32AutomationProvider.cs" Link="Win32AutomationProvider.cs" />
  </ItemGroup>
</Project>
