<Project>
  <Target Name="DorotiExcludeStockAndroidSkiaRuntime" AfterTargets="ResolvePackageAssets" Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">
    <ItemGroup>
      <NativeCopyLocalItems Remove="@(NativeCopyLocalItems)" Condition="'%(NativeCopyLocalItems.NuGetPackageId)' == 'SkiaSharp.NativeAssets.Android'" />
      <RuntimeTargetsCopyLocalItems Remove="@(RuntimeTargetsCopyLocalItems)" Condition="'%(RuntimeTargetsCopyLocalItems.NuGetPackageId)' == 'SkiaSharp.NativeAssets.Android'" />
    </ItemGroup>
  </Target>
  <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
    <Content Include="$(MSBuildThisFileDirectory)..\nativeAssets\win-x64\graphite\*" Link="graphite\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <DorotiLaunchDependency Include="$(MSBuildThisFileDirectory)..\nativeAssets\win-x64\graphite\libDorotiGraphite.dll" />
  </ItemGroup>
</Project>
